### ISSUE TITLE
[Feature Request] Raspberry Pi 4 support (aarch64)

### ISSUE THREAD

**Issue by tam481** [pawelmalak/flame#107]
Hello,
Please support aarch64 in a future release. I tried running this on my Raspberry Pi 4 running x64bit OS and I keep getting "standard_init_linux.go:228: exec user process caused: exec format error" which when I researched found to be caused by lack of architecture support

Thank you in advance

**Comment by K4CZP3R** [comment]
Same, here multiarch tag works on aarch64.
