### ISSUE TITLE
[Feature Request] Custom/Rotating background

### ISSUE THREAD

**Issue by Coderdude112** [pawelmalak/flame#115]
Hello! I have been loving flame and am now using it daily thanks so much!!

I think that adding the option to upload files to flame that will be used as backgrounds could be a nice way to add some more customization to flame.

If say 10 images were uploaded, the user could set it up so every day it selects a new image and shows that as the background instead of solid colors.

**Comment by nickstanko** [comment]
Quick hack for background images

`body {
   background: url('https://source.unsplash.com/1920x1920/?sky,clouds') no-repeat;
   background-size: cover;
}
body > div {
  background: rgba(0,0,0,0.8);
  min-height: 1200px;
}`

**Comment by rpluto** [comment]
Perfect it works for me!

**Comment by Coderdude112** [comment]
Is there a way to force the css to refresh? Ive tried inspect > network tab (disable cache) and refreshing but its really inconsistent

**Comment by pawelmalak** [comment]
@Coderdude112 Are you hosting Flame behind reverse proxy?

**Comment by Coderdude112** [comment]
Yep, behind NGINX proxy manager with cache common assets turned on. I'm assuming that's what the deal is. thanks @pawelmalak

**Comment by pawelmalak** [comment]
Yes, caching is probably the problem here. I had to disable `Cache Assets` in NPM and set cache level to `Bypass` for `flame.css` file in my Cloudflare page rules.

**Comment by Coderdude112** [comment]
Alright, I'm closing this as I was able to use the following css within the custom css tab of the Flame dashboard: (I did have to disable caching on NGINX proxy manager)

```css
body {
    background: url('[REDACTED URL]') no-repeat;
    background-size: cover;
}
body > div {
    background: rgba(0,0,0,0.8);
    min-height: 100vh;
}
```

The only change was spacing, and the min-height from a direct pixel value to 100vh which is the height of the window as a variable
