### ISSUE TITLE
Traefik Integration

### ISSUE THREAD

**Issue by Seishirou101** [pawelmalak/flame#130]
previous closed issue #102 

traefik integration was added with #112 but not sure if it actually works or if theres something special to enable it

**Comment by pa-sowa** [comment]
Code looks good, should work.
So in case of traefik enabled containers one needs to add only flame.name and flame.type labels to make the container visible in flame.
I already have a code that allows exposing all traefik enabled containers without any additional labels. I will create more PRs in the future.

**Comment by Seishirou101** [comment]
No luck, I'm afraid, but I think it may be related to me attempting to only give it socket proxy for the docker entry point. Is there a proper way to give flame access through a socket proxy?

**Comment by pa-sowa** [comment]
Could you include the flame and traefik labels for a container that doesn't work? (you can replace domain with host.com for privacy reasons)

**Comment by Seishirou101** [comment]
I actually use an env variable for the domain name would that cause issues? Here is an example of one that doesn't work as requested. Nothing gets added to my flame page as far as I can tell
```
labels:
      - "traefik.enable=true"
      - "diun.enable=true"
      - "flame.type=application" # "app" works too
      - "flame.name=komga"
      # HTTP Routers
      - "traefik.http.routers.komga-rtr.entrypoints=https"
      - "traefik.http.routers.komga-rtr.rule=Host(`komga.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.komga-rtr.middlewares=chain-no-auth@file"
      ## HTTP Services
      - "traefik.http.routers.komga-rtr.service=komga-svc"
      - "traefik.http.services.komga-svc.loadbalancer.server.port=8080"

**Comment by modem7** [comment]
> I actually use an env variable for the domain name would that cause issues? Here is an example of one that doesn't work as requested. Nothing gets added to my flame page as far as I can tell
> 
> ```
> labels:
>       - "traefik.enable=true"
>       - "diun.enable=true"
>       - "flame.type=application" # "app" works too
>       - "flame.name=komga"
>       # HTTP Routers
>       - "traefik.http.routers.komga-rtr.entrypoints=https"
>       - "traefik.http.routers.komga-rtr.rule=Host(`komga.$DOMAINNAME`)"
>       ## Middlewares
>       - "traefik.http.routers.komga-rtr.middlewares=chain-no-auth@file"
>       ## HTTP Services
>       - "traefik.http.routers.komga-rtr.service=komga-svc"
>       - "traefik.http.services.komga-svc.loadbalancer.server.port=8080"
> ```

I can confirm that domain variables work normally (wasn't aware of Traefik integration, so did things manually, but the env vars work)

e.g.

```
      ## Flame Dashboard
      - flame.type=application # "app" works too
      - flame.name=DroneCI
      - flame.url=drone.$DOMAINNAME
```

**Comment by Seishirou101** [comment]
traefik integration works, after messing around I found out that it was not correctly connecting to my socket proxy (also was being dumb and didn't turn on "use docker api". Thanks

**Comment by robflate** [comment]
Sorry to resurrect this but how did you get it working with a docker socket proxy?

**Comment by Cartache** [comment]
In ordre to make it work, you need:
- configure your docker container with the socket-proxy network
- start flame
- go to settings -> docker -> docker host: socket-proxy:2375

![image](https://user-images.githubusercontent.com/46925770/147774417-20dc0a1b-884e-4f5f-9f1e-4e684b0cfc80.png)
