### ISSUE TITLE
Add "apple-touch-icon" element to client

### ISSUE THREAD

**Issue by declan-wade** [pawelmalak/flame#131]
Greetings,

Loving this app so far!

It would be great if the iOS 'add to homescreen' element was supported by using the following in the `index.html` file:

`<link rel="apple-touch-icon" href="%PUBLIC_URL%/favicon.png">`

It would just needed to be inserted into the `<head>` section with a png file in the parent directory. Happy to test if required!

Thanks,

**Comment by edasque** [comment]
Yes, this would be lovely
