### ISSUE TITLE
How to backup bookmarks?

### ISSUE THREAD

**Issue by RobertBerger** [pawelmalak/flame#132]
I just reinstalled `openmediavault` where I currently run `flame`, and apparently lost all my bookmarks.  Is there an easy way to backup I guess the `db` of flame so I could import it to another installation?

**Comment by pawelmalak** [comment]
Apps and bookmarks are stored in `db.sqlite` file inside app `/data` directory. You can backup that file manually if you want. If you however deleted or overwritten that file, then your data is gone.
