### ISSUE TITLE
init error on portainer

### ISSUE THREAD

**Issue by chuckiton** [pawelmalak/flame#133]
hi, trying to install flame using a stack in portainer on Raspbian gives me this error as flame tries to launch:

standard_init_linux.go:228: exec user process caused: exec format error

any ideas?

**Comment by audibleblink** [comment]
You using the `flame:multiarch` tag? 
If so, what version of Pi?

**Comment by pawelmalak** [comment]
Hi @chuckiton Were you able to solve your problem? As @audibleblink said, this error usually occurs when trying to run `flame:latest` on ARM architecture. You should build your own image using `Dockerfile.multiarch` or pull it from `pawelmalak/flame:multiarch`

**Comment by chuckiton** [comment]
Hi! Yes I managed to fix it this way. Thank you for your help.
