### ISSUE TITLE
Settings link gone after adding the first application

### ISSUE THREAD

**Issue by Horuyuki** [pawelmalak/flame#135]
Thank you for this nice home page project!

I cannot go to the settings to add apps after the first one is adding with a hyperlink and instead have to manually type in /applications.

Is there a way to preserve a button to reach there quickly after the first one has been added instead of typing it in? Like a gear cog icon?

**Comment by pawelmalak** [comment]
You can access apps and bookmarks by clicking on the section headlines:
![links](https://user-images.githubusercontent.com/24780509/139742094-2885b50e-7438-44c9-bd4e-fe82050de3ee.png)

**Comment by Horuyuki** [comment]
> You can access apps and bookmarks by clicking on the section headlines:
> 
> ![links](https://user-images.githubusercontent.com/24780509/139742094-2885b50e-7438-44c9-bd4e-fe82050de3ee.png)

Yes indeed, I found out after further messing with the app.

**Comment by Horuyuki** [comment]
Yes indeed, I found out after further messing with the app.
