### ISSUE TITLE
[Bug] Custom CSS: BookmarkTable_Message__V57ZN should be replaced by AppTable_Message__3HoM_

### ISSUE THREAD

**Issue by AzamServer** [pawelmalak/flame#140]
[Bug] Custom CSS: BookmarkTable_Message__V57ZN should be replaced by AppTable_Message__3HoM_
Reason: Consistency
AppTable_Message__3HoM_ Location: Go to Application Page, Press "Edit" Button, Text is "You can drag and drop single rows to reorder application"
BookmarkTable_Message__V57ZN Location: Go to Bookmark Page, Press "Edit Catagories" Button, Text is "You can drag and drop single rows to reorder categories"

**Comment by pawelmalak** [comment]
It's not possible. Class names are generated automatically by React following `ParentComponent_Class_Hash` rule. Because AppTable and BookmarkTable are two separate components, all of their children will have classes automatically scoped to each of them.
