### ISSUE TITLE
How do you import bookmarks from Browser export?

### ISSUE THREAD

**Issue by oregonpillow** [pawelmalak/flame#141]
All web browsers export and import bookmarks in html format. Is there no way to currently import bookmarks from a browser export?

**Comment by pawelmalak** [comment]
Not at this moment but I will take a look at possible implementation.

**Comment by crispybegs** [comment]
did this ever happen?

**Comment by oregonpillow** [comment]
> did this ever happen?

only something hacky that i committed a while ago: https://github.com/pawelmalak/flame/blob/master/.dev/bookmarks_importer.py .
