### ISSUE TITLE
Where to place kubeconfig in docker container

### ISSUE THREAD

**Issue by PhilippCh** [pawelmalak/flame#143]
Hi there,

I'm running Flame as a docker container inside my own Kubernetes cluster. I've tried placing my kubeconfig file at /root/.kube/config to no avail. The logs show a constant stream of 
```
[2021-11-05 11:17:28.199 UTC+0] [ERROR] Can't connect to the Kubernetes API
```

I've changed the server in the config file to `server: https://10.43.0.1:443`, which equals the KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT environment variables inside the container. Is there any way to get debug output from the kubernetes-client library?

**Comment by onedr0p** [comment]
You should not need to put your kubeconfig the the container, flame should be smart enough to use the rbac / service account to query ingresses. I could be completely wrong about the app doing this, but that is the way it _should_ be

**Comment by PhilippCh** [comment]
Perfect, the ServiceAccount that was created by the k8s-at-home common library chart for me was missing the required permissions for the Ingress namespace. Thanks a lot!
