### ISSUE TITLE
[Feature Request] Aphabetical Bookmarks

### ISSUE THREAD

**Issue by modem7** [pawelmalak/flame#156]
Requesting the ability to sort bookmarks alphabetically under categories much like Apps can be.

**Comment by pawelmalak** [comment]
But they are already by default. In fact, this is the only supported mode at the moment.

**Comment by modem7** [comment]
> But they are already by default. In fact, this is the only supported mode at the moment.

Huh, something must be going weird:

![image](https://user-images.githubusercontent.com/4349962/140771976-c341191a-ffa2-4175-8e68-4271021decef.png)

**Comment by modem7** [comment]
Ignore.

I'm a twat. Didn't f5 the browser.

Closing due to stupidity.
