### ISSUE TITLE
Replacing greeting with title

### ISSUE THREAD

**Issue by mark4409** [pawelmalak/flame#161]
I guess this is a feature request. I can see in the settings that there's an option to show or hide the greeting. There's also an option to set a custom title. What I'm proposing is reworking that a little and have the option to display the title instead of the greeting.

Alternatively just an option to edit the greeting would be nice. I think having the choice of a hard coded greeting or no greeting at all is a little restrictive.

**Comment by mark4409** [comment]
Clearly a hack but for the moment I'm getting around it by adding the following to the custom CSS section:

```
span[class*='Home_HeaderMain'] h1 {
    visibility: hidden;
}

span[class*='Home_HeaderMain'] h1:after {
    content: "My Custom Dashboard";
    visibility: visible;
    display: block;
    margin-block-start: -1em;
}
```

**Comment by mark4409** [comment]
I must have grabbed it just before you did that!

**Comment by pawelmalak** [comment]
You should also get notification if there is a new version available. 

If you want to have only one message to be always displayed, you need to set it like that: `message;message;message;message`.

**Comment by mark4409** [comment]
Just done a git pull and rebuilt and now have the option. Thanks.
