### ISSUE TITLE
Trouble with Material Design Icons integration

### ISSUE THREAD

**Issue by Brancliff** [pawelmalak/flame#164]
There's no way I'm doing something wrong here, right? Like, it's just as easy as typing in the name of the icon and that's it, right?

Here are some of the icons I tried that just gave me the "circle with a line through it" 'no' icon instead:

- account-clock
-  align-horizontal-left
-  alpha-w-circle
-  arrow-collapse-down
-  cloud-check-outline
-  email-multiple

I know the icon integration itself works - it suggests book-open-outline and that's fine. Airplane works. I'm not sure if there's a pattern to what works and doesn't work- or why some of them don't work in the first place.

I'm running this through Container Station on QNAP's QTS if that means anything

**Comment by pawelmalak** [comment]
Hi. I just checked and all these icons work for me. Are you using the latest app version? And are you sure that icon name doesn't contain any spaces? So instead `account-clock` it's ` account-clock` or `account-clock `.

**Comment by pawelmalak** [comment]
Hi. I just checked and all these icons work for me. Are you using the latest app version? And are you sure that icon name doesn't contain any spaces? So instead `account-clock` it's ` account-clock` or `account-clock `.
