### ISSUE TITLE
[Feature Update] Make Option for Default Theme

### ISSUE THREAD

**Issue by AzamServer** [pawelmalak/flame#165]
Allow users to have an option to make their own default theme for their own Flame dashboard. 
This option can be configurable in settings. 
Of course, the option for other themes should still be there, but the default theme only chooses a theme for when a new user loads a Flame Dashboard.

Example:
User -> Custom Theme: Cloud -> On First Time Load: Theme is: Cloud -> User then chooses theme Tron -> Theme for said user will now be Tron, unless changed

**Comment by joshbergm** [comment]
+1

**Comment by nicktfried** [comment]
How do I set a default theme by chance?
