### ISSUE TITLE
possible bug? all applications become unpinned when visiting flame from bookmark

### ISSUE THREAD

**Issue by kavemang** [pawelmalak/flame#168]
When I visit the dashboard from bookmark all applications become unpinned and only bookmarks are showing. The browser is Vivaldi though not sure if that matters

**Comment by pawelmalak** [comment]
Are you using Docker integration?

**Comment by kavemang** [comment]
> Are you using Docker integration?

Thats a good point going to turn that off and test as i didnt add labels to my containers
