### ISSUE TITLE
Details about search bar shortcuts in wiki

### ISSUE THREAD

**Issue by vp-lab** [pawelmalak/flame#170]
Flame version: 1.7.4 - installed in docker.

When the search bar it's out of focus, what button/buttons I need to press to focus search bar? 

- search something in local search [focus it's on search bar]
- if I click the app, it'll open the website, close the app, and the search bar it's out of focus.
- if I click ESC - it'll delete what it's on search bar but not focus the status bar.

How can I focus with keyboard shortcuts? 
I searched all wiki and nothings pops.

https://github.com/pawelmalak/flame/wiki/Search-bar

**Comment by pawelmalak** [comment]
There is no shortcut to focus the search bar right now, but it should be easy to add.

Any suggestion which button should do that?

**Comment by vp-lab** [comment]
Mhm, maybe a dropdown menu like on **Default Search Provider** with multiple buttons like:

- /
- \
- `
- ESC [to delete what's on the search bar and focus it to search it again]

Or if you can to implement custom focus button, but for me / \ ` ESC it's enough.
