### ISSUE TITLE
Export Feature

### ISSUE THREAD

**Issue by dnburgess** [pawelmalak/flame#171]
Is there any chance we could get an export feature in this application?

**Comment by pawelmalak** [comment]
Hi. Why would you need that? All data is already stored in the sqlite file.

**Comment by dnburgess** [comment]
So that if I need to redeploy on another server or just have a backup of my settings I don't have to go through and set up all my settings/links, etc. again.

**Comment by pawelmalak** [comment]
Everything is saved in the mounted volume. Can you just copy files from there?
```nothing
/uploads - all uploaded icons if any
config.json - your whole app config
customQueries.json - user defined search engines
db.sqlite - all apps, categories and bookmarks
flame.css - custom styles
```

**Comment by dnburgess** [comment]
I suppose I could, but I set a volume and mounted it to that rather than mounting it to a folder on my server. I guess I'll have to redeploy using a mounted folder instead of a mounted volume...
