### ISSUE TITLE
Whoogle as search engine? 

### ISSUE THREAD

**Issue by martinkath** [pawelmalak/flame#172]
Heya, great work! 

Went through https://github.com/pawelmalak/flame/wiki/Search-bar and was wondering how I could implement my docker based https://pypi.org/project/whoogle-search/ installation. Would that be possible?

**Comment by pawelmalak** [comment]
You can add your own search engines. Just go to Settings > Search > Custom search providers. Then you only need to provide search URL template.

For example, I have found [this](https://whoogle.sdf.org/) public instance of Whoogle and if I search for `github` I get this url `https://whoogle.sdf.org/search?q=github`. So you would just provide this `https://whoogle.sdf.org/search?q=` as a search template.
