### ISSUE TITLE
[Bug] Search Engine cannot be changed to custom search engine

### ISSUE THREAD

**Issue by AzamServer** [pawelmalak/flame#176]
Bug: Search Engine cannot be changed to custom search engine
Info: Search engines that are already present can be selected from the drop-down menu. However, when a custom search engine is selected from the drop down, Flame will pick the search engine which is the most similar to what the custom search engine is named.
Example: When Whoogle is selected from the drop-down menu, Wikipedia will be automatically chosen instead.

**Comment by pawelmalak** [comment]
What prefix are you using for Whoogle? Perhaps it is in conflict with Wikipedia prefix `/w`

**Comment by AzamServer** [comment]
Sorry for the late response. I had no idea you responded. You were correct, and I when I changed the prefix, it worked. Thanks so much!
