### ISSUE TITLE
after update to flame 2.0.0 i can't add applications

### ISSUE THREAD

**Issue by swoop124** [pawelmalak/flame#177]
Hi all,

i just have updated my flame-docker instance but now i can not add new applications, bookmarks yes but no apps.

the update process was like that:
stop docker container
recreate (in portainer)

After that i have recreated the container with a new stack in a new directory. But nothing changed.
I still can only add Bookmarks.

Any ideas?

regards

**Comment by pawelmalak** [comment]
Ok. I think I found the problem. Are you trying to create app with custom icon (from file)?

**Comment by swoop124** [comment]
yes.

**Comment by swoop124** [comment]
OK, i can now add now Apps, but i have to use a image_url.
after the creation of a "dummy" App i can change it to a custom image.

but where is the problem when i want to use a custom image at creationtime?

**Comment by pawelmalak** [comment]
It's the problem with the app. I'm already working on the fix.

**Comment by pawelmalak** [comment]
Just pushed updated images for both `latest` and `multiarch` tags. Can you pull it and try adding new app again?
