### ISSUE TITLE
Can't display applicatoins or bookmarks, constantly shows loading icon

### ISSUE THREAD

**Issue by Horuyuki** [pawelmalak/flame#179]
Logged in with 2 week duration and 1 year. Page keeps loading and apps doesn't show.
No bookmarks either.

I was thinking of cache so used private window, still couldn't load.

Version 2.0, portainer stack.

**Comment by pawelmalak** [comment]
Any errors in:
- browser console
- container logs?

**Comment by Horuyuki** [comment]
> Any errors in:
> 
>     * browser console
> 
>     * container logs?

Logs look ok:
```
[2021-11-15 15:00:39.477 UTC+0] [INFO] Executing pending migrations


[2021-11-15 15:00:39.531 UTC+0] [INFO] Connected to database


[2021-11-15 15:00:39.537 UTC+0] [INFO] Socket: listen


[2021-11-15 15:00:39.537 UTC+0] [INFO] Server is running on port 5005 in production mode
```

Console Error:
```
XHRGEThttps://home.example.com/api/categories
[HTTP/2 401 Unauthorized 64ms]

XHRGEThttps://home.example.com/api/apps
```

That would mean I can no longer use nginx basic auth with it right? Currently it is implemented with nginxproxymanager.

**Comment by Horuyuki** [comment]
Alright boys no more nginx basic auth for your flame.
