### ISSUE TITLE
[Feature Request] LDAP auth for UI

### ISSUE THREAD

**Issue by joshbergm** [pawelmalak/flame#184]
Hi there!

First of all thank you for this amazing tool!
Could you integrate LDAP auth for the UI?

I'm using this tool in my semi enterprise environment and would like to give access to only the people who need it.
LDAP with group based auth would be nice!

For the peeps who don't use this tool in enterprise alike environments, a toggle to turn on and off would be nice!

Thanks in advance!

Kind regards,

Joshua Bergman

**Comment by nomandera** [comment]
With the reddit post announcing version 2.0 I tried flame and I really like it. I then went on the hunt to find if multiuser support is planned and found this post.

LDAP is IMHO the future of self hosting held back only by lack of a truly simple drop in back-end although [glauth](https://github.com/glauth/glauth) or [LLDAP](https://github.com/nitnelave/lldap) are almost there.

**Comment by JaneJeon** [comment]
> held back only by lack of a truly simple drop in back-end although glauth or LLDAP are almost there.

I know this isn't the point of the issue but holy shit do I agree with you. I feel like LDAP -> Authelia -> SSO (e.g. OIDC) is **THE** way to go, but setting up dockerized LDAP myself is such a pain in the ass that I'm scared away from doing LDAP myself.

**Comment by nomandera** [comment]
With the closure of https://github.com/pawelmalak/flame/issues/231 this request likely needs closed as well.
