### ISSUE TITLE
Ability to reorder Bookmarks

### ISSUE THREAD

**Issue by TheSamDickey** [pawelmalak/flame#187]
Hello!  I am an avid flame user and love the project.  Thank you to everyone who has contributed to this; it is truly the best dashboard out there imo.

## Feature Request:
It would be amazing if bookmarks could be reordered, in the same way that applications and bookmark categories can be reordered.  I have quite a few bookmarks, and there are a handful I really wish I could move around.

Has this been discussed before?  I would be interested to know if others would also find this useful.

Note: I am unsure if it has to do with permissions, but I am unable to add a Feature Request label to this.  Sorry about that!

**Comment by Brancliff** [comment]
Seconding this - you can click-and-drag to reorganize your applications, but you can't reorganize your bookmarks at all. It seems like an odd omission

**Comment by ae5960e8-a6fc-491f-b252-898ecf59af95** [comment]
I was surprised that this hasn't been implemented when the order of applications can be changed so easily in the same way we'd expect bookmarks to also. Please consider adding this functionality.

**Comment by pawelmalak** [comment]
> you can click-and-drag to reorganize your applications, but you can't reorganize your bookmarks at all. It seems like an odd omission

> I was surprised that this hasn't been implemented when the order of applications can be changed so easily

That's because apps exist in a single dimensional array so reordering them comes down to simple index value changing. Bookmarks however, exist in two dimensional array. They are nested within categories array which is also single dimensional. Because we have one table to access and edit all bookmarks it's not possible to implement custom order here (can't set shared order index value between multiple arrays). The only way it could be implemented is to move bookmark editing into separate table. So to edit or reorder bookmarks you would have to first choose category and then access its bookmarks for edit.

**Comment by TheSamDickey** [comment]
@pawelmalak Thank you for the insight on this.  I feel like the requirement of clicking into category, then accessing its bookmarks for edits is a pretty intuitive way of doing it.

Do you think that this addition would be okay to have?  If so, is this something that I should attempt to do and make a PR for?

**Comment by Brancliff** [comment]
Oh, I'm glad there's a reasonable technical explanation for it. I don't know how this sort of stuff works - I'm not a software engineer, I'm just some kid with a NAS

But- not only would a separate table for bookmarks fix the inability to reorganize them, I think it'd be a great change anyway! Editing your bookmarks can get more cumbersome the more of them you have - if you have a long list of them, there can be a lot of scrolling up and down to do a lot of editing. You can try to ctrl + F to jump to a specific one, but if you need to edit more than one, it can only help so much.

Right now, clicking on the name of a bookmark category doesn't do anything (either from the main menu or the bookmarks menu), so I think that would be a good place to put it.
