### ISSUE TITLE
Allow Application and Bookmark to provide http[s]

### ISSUE THREAD

**Issue by rgriffogoes** [pawelmalak/flame#19]
"https-only" application will work only if a automatic redirect is in place (somehow a good practice).  

Is there any reason to not allow users to define proper protocol? (which could even be something other than http[s])

**Comment by ValentinPifu** [comment]
You can read this solved isssues. Right now don't have a proper parser for URL.
https://github.com/pawelmalak/flame/issues/5

**Comment by rgriffogoes** [comment]
Really the same as #5  
Closing as duplicated, sorry

**Comment by rgriffogoes** [comment]
I'm confused if this was fixed on that pull request or not
IF not, I suggest to reopen this and flag it as enhancement
