### ISSUE TITLE
Lost all data after update to version 2.0

### ISSUE THREAD

**Issue by lenovin** [pawelmalak/flame#191]
Is there a way to update the docker without losing the data? I had to do all the hard work again after the update. 
or pls give a provision to **take backup and then restore it after the upgrade**.

Anyways love your project, looking for this kind of app for a long time.

**Comment by pawelmalak** [comment]
All your data is in the mounted volume. Restarting or updating the container should have no effect on this. Can you check if there any files in your host directory?

**Comment by juan11perez** [comment]
@pawelmalak 
I didn't loose my data, but now there's no option to edit bookmarks or applications.
If I click on say the applications header it no longer presents an add/edit option

**Comment by pawelmalak** [comment]
#218

**Comment by lenovin** [comment]
lost all added applications and bookmarks after update...

used dockupdater to update the containers... Pls help
