### ISSUE TITLE
[Feature Request] Add Bing search to the drop down menu.

### ISSUE THREAD

**Issue by dhrandy** [pawelmalak/flame#193]
Just wondering if Bing could be added to the search drop down menu.  I wasn't sure how to add it to the custom search.

**Comment by pawelmalak** [comment]
Have you tried using this a as url template: `https://www.bing.com/search?q=`?

**Comment by pawelmalak** [comment]
Have you tried using this as a url template: `https://www.bing.com/search?q=`?
