### ISSUE TITLE
Custom headers looking weird when using Romanian characters

### ISSUE THREAD

**Issue by sabinM1** [pawelmalak/flame#195]
Hello, it seems that the current font doesn't support some characters from the Romanian language. When using characters like *ă*, *â*, *ș* etc. the headers look like the following:
![image](https://user-images.githubusercontent.com/46656298/142046387-808cb711-d365-49b3-901f-147f24df0ed7.png)

I'm running the latest (as of 16 of november with the 2.0.0 update) version of Flame using the multiarch tag from docker. I've tested this on Firefox 94 on Windows and Linux (`Mozilla/5.0 (X11; Linux x86_64; rv:94.0) Gecko/20100101 Firefox/94.0`), also on Chromium 96 (`Version 96.0.4664.45 (Official Build) Arch Linux (64-bit)`).

I think this could be fixed by having an option to change the font for the headers or by replacing the default font with something else.

**Comment by pawelmalak** [comment]
You can set custom font using CSS:

```css
* {
  font-family: "Comic Sans MS", sans-serif !important;
}
```

Here is the list of web safe fonts:
```none
Arial
Arial Black
Verdana
Tahoma
Trebuchet MS
Impact
Times New Roman
Didot
Georgia
American Typewriter
Andalé Mono
Courier
Lucida Console
Monaco
Bradley Hand
Brush Script MT
Luminari
Comic Sans MS
```

**Comment by sabinM1** [comment]
All right, I guess using custom CSS works too. Thanks for the help!
