### ISSUE TITLE
Opening flames dashboard also opens the default search provider site in a second tab

### ISSUE THREAD

**Issue by maxwassiljew** [pawelmalak/flame#199]
Opening flames dashboard also opens the default search provider site in a second tab. 
For example for me Wikipedia, a second tab is opened with this url https://en.wikipedia.org/w/index.php?search=

version 2.0.0

**Comment by pawelmalak** [comment]
So when you open the app, say directly from the url, two pages open? One is flame and the other is your default search provider? You don't use search bar just open the app?

Can you post your app config? You can get it from `your.flame.url/api/config`. You can delete weather module settings if you want.

**Comment by maxwassiljew** [comment]
yes, exactly. Two tabs are opened after entering the url in the browser url bar and pressing enter. Maybe some misconfiguration on my side? I also tested using the private mode in Safari and everything worked as expected. 

`{"success":true,"data":{"customTitle":"Dashboard","pinAppsByDefault":true,"pinCategoriesByDefault":true,"hideHeader":false,"useOrdering":"createdAt","appsSameTab":false,"bookmarksSameTab":false,"searchSameTab":false,"hideApps":false,"hideCategories":false,"hideSearch":false,"defaultSearchProvider":"w","dockerApps":true,"dockerHost":"localhost","kubernetesApps":false,"unpinStoppedApps":false,"useAmericanDate":false,"disableAutofocus":false,"greetingsSchema":"Good evening!;Good afternoon!;Good morning!;Good night!","daySchema":"Sunday;Monday;Tuesday;Wednesday;Thursday;Friday;Saturday","monthSchema":"January;February;March;April;May;June;July;August;September;October;November;December","showTime":true}}`

**Comment by pawelmalak** [comment]
New instance with your config is working fine on Opera, Chrome and Firefox. If it's working for you in the incognito mode, maybe you have some browser extension that could somehow interact with the search bar?
