### ISSUE TITLE
Saving latitude and longitude instead of providing API secret key throws error 

### ISSUE THREAD

**Issue by Nischay-Pro** [pawelmalak/flame#2]
In the settings panel, when saving latitude and longitude and leaving API key empty throws both a `Success Settings Updated` and an `External API Request Failed` error.

I'm using the docker build with the latest tag.

**Comment by Nischay-Pro** [comment]
Ah. Perhaps maybe add some instruction on how to use this feature in the README. On first glace I thought just specifying geographic co-ordinates was enough. Some sort of text validation when user fills up partially to inform user that the field is compulsory if they wish to use the weather feature.

**Comment by pawelmalak** [comment]
Good idea. Will add information about it next to the input field and emit notification if lat&long are set but api key is missing.
