### ISSUE TITLE
[Feature Request] Brief description rather than URL

### ISSUE THREAD

**Issue by nomandera** [pawelmalak/flame#201]
For my family the URLs in the application section of the GUI are not required.

For us at least they are:

- samey... all being variations of `app.ourdomain.xxx`
- surplus to demand since mouse-overs display the URL anyway
- makes showing off the panel much harder as every URL needs redacted in the screenshot before posting publicly
- subject to shoulder surfing.

I suggest an optional new field called `Brief description` be added, limited in length to not break the interface design.

The following is a before and after mock up

![image](https://user-images.githubusercontent.com/1133344/142382007-c007ac4c-6155-4120-8e3d-57190de13161.png)

![image](https://user-images.githubusercontent.com/1133344/142382057-902d97d5-7f64-4f4b-af1b-8e1effccc6f2.png)

If this is off interest you may also consider the fact that most users will be self hosters and a few hundred projects (if even) will cover the vast majority of their applications. It is totally viable to crowd source a list of projects so that the OOTB exprience for flame is even slicker.

**Comment by thehijacker** [comment]
Second vote for this. Would make it more pleasent to the eyes instead of local IP URL.

**Comment by Digitalhour** [comment]
Agree, this would be nice

**Comment by thehijacker** [comment]
Anyone else things this is a good idea? Maybe to discuss further?

@pawelmalak can you consider this? Now still using Homer, but I would switch to Flame instantly if it has this feature.

**Comment by oester** [comment]
Another vote for this.

**Comment by lancebarnette** [comment]
Great feature. Thanks for all the work.

**Comment by nomandera** [comment]
Confirmed working as expected

![image](https://user-images.githubusercontent.com/1133344/146634794-41c7e317-07fd-4113-8aed-3b31bad4d557.png)

Nice work.

**Comment by uberjew666** [comment]
Is there a label such as flame.description for those setting the values using docker/kubernetes API?
