### ISSUE TITLE
traefik basic authentication broken with v2

### ISSUE THREAD

**Issue by jnnngs** [pawelmalak/flame#202]
I use traefik to provide basic authentication in front of flame (loving it BTW!), which now continually prompts for the user/password details with the latest flame version. Reverting back to flame:1.7.4 removes the new issue.

I'm guessing it's a cookie issue somewhere with flame?

Flame docker labels used for traefik:
traefik.http.middlewares.traefik-basicauth.basicauth.users : USER:PASSWORD
traefik.http.middlewares.traefik.addprefix.prefix : traefik-basicauth

traefik basicauth doc link: https://doc.traefik.io/traefik/v2.0/middlewares/basicauth/

Happy to provide additional info and test any fixes.

**Comment by pawelmalak** [comment]
I know nothing about traefik so I won't be much of a help here. Hopefully someone with similar setup will be able to help.

Also, someone reported that he had to disable nginx basic auth for v2.0: https://github.com/pawelmalak/flame/issues/179#issuecomment-969001733

**Comment by jnnngs** [comment]
Its probably the same issue then. I'll take a look and compare 1.7.4 and 2.0 cookies.

I'll report back...

**Comment by Gallardo26** [comment]
Having similar issue but I'm using HAproxy ACL with http-request auth. Have no issue with other services until I updated Flame to the latest.

**Comment by jnnngs** [comment]
It seems a conflict with the new password authentication - https://github.com/pawelmalak/flame/wiki/Authentication

I'm still looking into it...

**Comment by jnnngs** [comment]
Its a clash with JWT and the Authorization header field. Traefik, nginx and HAproxy use this header field for basic auth, but flame is using it for version 2.0.

I guess a good conclusion would be for flame to implement an optional setting that offers the same username/password basic auth when first launching?

Feature Request?

**Comment by ekremparlak** [comment]
I change Flame's Authorization header to Authorization-Flame here: https://github.com/ekremparlak/flame/commit/04822a48e89ad0c33cfebed939f645a4e634eca6
Its seem to working but the problem i found when you tried to open the api directly like https://example.com/api/apps it doesn't work.

**Comment by ekremparlak** [comment]
Looks like https://example.com/api/apps was same without changes

**Comment by jnnngs** [comment]
Is there a possible fix?

**Comment by pawelmalak** [comment]
Can anyone pull `pawelmalak/flame:dev` and check if it's working with your basicauth setup?

**Comment by jnnngs** [comment]
Yes, ill test it now ...

**Comment by jnnngs** [comment]
Confirmed working perfectly using basic auth on Traefik !!

:)

**Comment by pawelmalak** [comment]
That's great. I'll have to test a few more things but it should be out with the next version.
