### ISSUE TITLE
Two different views when viewed locally vs externally

### ISSUE THREAD

**Issue by raviwarrier** [pawelmalak/flame#203]
I don't know if this is an issue with Flame, but I am hoping you could help me.

When I view the page locally (http://192.168.1.x:5005), I see the updated (all apps and applied theme), but when I view externally (https://apps.mydomain.com) I see an old view with the newly added apps missing and the page using a theme that I used 2 days back).

I use raspberry pi and have installed flame via docker. For external access I use nginx proxy manager. And I have tested this on Firefox and Microsoft Edge with same results.

In Nginx, I have checked and "Cache Assets" is off. I have cleared the cache in my browsers and still no change. I have restarted the container and raspberry pi itself and still no change.

I can't think of anything else to do to fix this. Can you help?

It's not an urgent/high priority issue, so please reply when you are free-er. 

Cheers and have a nice day,
W.

PS: Here are the screenshots - https://imgur.com/a/tjm67JC

**Comment by pawelmalak** [comment]
Are you using latest feature to hide some apps behind authentication?

Also, theme will be only saved for the current url. So if you host flame on port `5040`, change theme and then restart app on port `5041` theme will be changed back to default.

**Comment by raviwarrier** [comment]
I have logged in, but I haven't hidden any apps (checked them and they all say "Visible (anyone can access it)".

Since you mentioned the ports, let me know if this might be the issue:

Day before my home assistant crapped out and since I couldn't fix it, I re-installed my entire RPI, which includes Flame. This time (yesterday) when I installed Flame, I left the ports to default (5005:5005), but I can't be entirely certain that I might have used 5005 in my earlier install before the crash. 

But since my appdata is stored on my ssd (which is used to create data/config volumes), I didn't have to add all the apps/bookmarks again. But I did add a few new ones after (the ones shown as missing). 

Maybe, it could be the port thing. Do you know if there's a way to fix this without having to re-add all my apps and bookmarks? If not, my only option is to do a clean install of Flame (which I'd like to avoid).

Cheers for replying. Hope you staying safe.

**Comment by pawelmalak** [comment]
No, ports shouldn't have any impact on your app content. All data is stored in `db.sqlite`.

- Are you getting any errors in the browser console or container logs?
- Can you go to `flame.url/api/apps` and try to find your missing apps there?
- Do you have access to your `db.sqlite` file?

**Comment by raviwarrier** [comment]
No errors on browser. Logs, I can't say; since my reinstall yesterday, my portainer containers (some of them) just don't show logs (it's another thing on my 'fix-my-pi' list). But I'll check again and let you know in a bit.

And will check the uri you suggested too.

Yes, I can access my .sqlite file.

**Comment by raviwarrier** [comment]
Update:
1. Can't check logs - https://imgur.com/a/tT7NNcY
2. /api/apps is missing two applications that I see on flame.url:5005 but has the same number of apps as the dashboard I see when I open an external link. (can send you the link and pastebin contents of the json file) over DM if you'd like.
3. What do you want me to do with the .sqlite file?

Also, a new issue (?) while I was trying to browse from my phone. As you can see the tabs have different icons (one is round and one is square). Thought you might want to know - https://imgur.com/a/ySSH4xB

**Comment by pawelmalak** [comment]
> What do you want me to do with the .sqlite file?

You can open your database with [DB Browser for SQLite](https://sqlitebrowser.org/) and check if missing apps are there.

**Comment by raviwarrier** [comment]
Yes, it does have the two missing app links.
![image](https://user-images.githubusercontent.com/42061703/142630142-3986a1b7-fe45-436d-b2de-3f206db78779.png)
So, what should I do now? Is there a way to fix or shall I just delete everything and start again?

BTW, thanks for all the support and patience so far. :)

**Comment by pawelmalak** [comment]
There is a `isPublic` column at the end. Do all of your apps have it set to `1`?

**Comment by raviwarrier** [comment]
No. In fact, it is set to True for some of them (the missing ones). Changed it to 1 and wrote changes. But no change in the external link. In fact, I opened it again and the values still remain 'True' instead of 1.

**Comment by raviwarrier** [comment]
I just fixed it. For the 4 apps that were set to True, I changed them to hidden (updated it) and then changed to visible before updating again. Now I have all my apps. And also updated the theme again.

I think you might want to check why the field was set to 'True' instead of 1. That could be a potential bug.

Thanks for helping with the fix. Have a wonderful evening.

**Comment by pawelmalak** [comment]
> I think you might want to check why the field was set to 'True' instead of 1. That could be a potential bug

I already found it and fixed it. Will be out with next version.

**Comment by pawelmalak** [comment]
> I think you might want to check why the field was set to 'True' instead of 1. That could be a potential bug

Already found and fixed it. Will be out with next version.
