### ISSUE TITLE
[Feature request] Option to select which tab to open a link in

### ISSUE THREAD

**Issue by raviwarrier** [pawelmalak/flame#204]
Since there are no buttons on the dashboard to add/edit apps or bookmarks, I have just created links to them in Bookmarks. The problem is that whenever I click on links for applications, bookmarks or settings, it opens them in new tabs. By the time I have finished editing or configuring, I am left with 5 or 6 tabs of Flame. I know I am stupid by "going back" to see how it looks and then returning to edit and that closing extra tabs is not a big problem, but:

Can we have an additional setting while creating/editing apps or bookmarks - open in "same tab/new tab (default)" to override the global "open in new tab" setting?

**Comment by pawelmalak** [comment]
What do you mean by:
> there are no buttons on the dashboard to add/edit apps or bookmarks

It's working fine for me:
![image](https://user-images.githubusercontent.com/24780509/142616105-0b45df73-e2f4-46f8-9db7-50eef8326c0f.png)

**Comment by raviwarrier** [comment]
I mean on the dashboard. The only way I could go to the two screens you shared is by typing /applications and /bookmarks in the address bar after the URL.

**Comment by raviwarrier** [comment]
I could be wrong (or most possibly need new specs), but other than the settings' cog icon on the bottom left, I couldn't find any internal navigation links/buttons.

**Comment by pawelmalak** [comment]
You can just click on the section name:
![image](https://user-images.githubusercontent.com/24780509/142621971-377be901-7cf5-4ffb-b414-8a3c01fc45c5.png)

**Comment by raviwarrier** [comment]
Ah! I didn't know of that! Thanks for the info. But, can we still have an option to allow opening of a bookmark/app in the same tab?

**Comment by pawelmalak** [comment]
#57
