### ISSUE TITLE
Addin g a widget?

### ISSUE THREAD

**Issue by JoBilert** [pawelmalak/flame#208]
Hi, i like the dashboard a lot, but I wonder if there's a possibility to add a widget of sorts.

Specifically, I would like to add a small area where I could display some "Picture of the Day".
Is there a way to do that via CSS?

**Comment by pawelmalak** [comment]
Sorry but there is not much room to place such widget without breaking the interface.

**Comment by JoBilert** [comment]
Oh, I think I phrased this in a way to be misunderstood. I didn't mean to cause you any additional work. Neither do I request the addition of a new element.

I was thinking about "abusing" something like the "bookmarks"-section or the weather-widget to display a picture.
I was hoping I could solve this with a CSS-override, but I am not really well versed in CSS, so I hoped someone here could tell me if that was possible.

I like the dashboard as it is.

**Comment by pawelmalak** [comment]
Perhaps it would be possible with CSS but it wouldn't be easy. If you have some API which provides image of the day you could use it as a background image of some div.
