### ISSUE TITLE
[Feature Request] Allow .ico + .svg to be set

### ISSUE THREAD

**Issue by modem7** [pawelmalak/flame#209]
In addition to #138, would it be possible to allow .ico and .svg in addition to jpeg, jpg, png?

Thanks!

**Comment by pawelmalak** [comment]
SVG is already supported

**Comment by Unkn0wnCreator** [comment]
Maybe automatically use favicon if no icon chosen

**Comment by modem7** [comment]
> Maybe automatically use favicon if no icon chosen

Was more thinking that I have a collection of icons, and some are .ico (https://github.com/modem7/MiscAssets) as it just makes it easier for myself at least (and some apps only provide the .ico)

**Comment by nomandera** [comment]
If there is scope to discuss this then there are curated asset lists ready made out there that could be consumed today.

https://github.com/linuxserver/Heimdall-Apps

A process to normalise to the white on transparent material design icons would be created but this should be simple enough to even be done on the fly.
