### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by mariushosting** [pawelmalak/flame#212]
**Deployment details:**
- App version [2.0.1]: 

---

**Bug description:**

If we hide Greetings, automatically we also hide Weather.

**Comment by pawelmalak** [comment]
It's not a bug. Setting name could be a little more descriptive but it's intended to hide both text and weather. If you remove greetings only, the weather widget just looks weird on its own:

![image](https://user-images.githubusercontent.com/24780509/142707722-d657d790-9dc4-42e3-9200-7f145232efbd.png)

**Comment by mariushosting** [comment]
So, in this case I think it will be ok to add something like this Hide Greetings and Weather not only greetings. :-)
Thank you Pawel!

**Comment by pawelmalak** [comment]
> Or..make a personalized greetings text message

You can already do it. Settings > Interface > Header > Custom greetings

**Comment by mariushosting** [comment]
Thank you I didn't see it!
