### ISSUE TITLE
[BUG] Flame hangs indefinitely

### ISSUE THREAD

**Issue by JaneJeon** [pawelmalak/flame#213]
**Deployment details:**
- App version [e.g. v1.7.4]: v2.0.1
- Platform [e.g. amd64, arm64, arm/v7]: x86-64
- Docker image tag [e.g. latest, multiarch]: latest

---

**Bug description:**

Even without any sort of authentication "on top of" flame (e.g. Authelia), flame always hangs and my gateway has to time it out.

---

**Steps to reproduce:**

Go to home.janejeon.com. I've opened it up to the public (with some really long and complex password, of course) just for this issue. You should see that it times out.

The config is here: https://github.com/JaneJeon/self-hosted/blob/master/config/homepage/docker-compose.flame.yml

And the logs show absolutely NOTHING:

```
[2021-11-20 01:20:49.228 UTC+0] [INFO] Connected to database
[2021-11-20 01:20:49.257 UTC+0] [INFO] Socket: listen
[2021-11-20 01:20:49.258 UTC+0] [INFO] Server is running on port 5005 in production mode
# There's no more entry, even if I kill it/restart it. I can see that port 5005 is indeed open, but the request isn't even being acknowledged by flame it seems like
```

I've disabled even my auth middlewares, and you can dig around the repo to see that the setting of flame is not wrong (e.g. the labels are exactly the same as https://github.com/JaneJeon/self-hosted/blob/master/config/docker-management/docker-compose.portainer.yml#L18, which is publicly accessible at portainer.janejeon.com)

I'm at my wit's end. Why does flame not even acknowledge the request?

**Comment by pawelmalak** [comment]
@JaneJeon Do you know what was causing that problem? Something with the app or the setup?

**Comment by JaneJeon** [comment]
networking xP
