### ISSUE TITLE
Feature request: ability to set the # of columns

### ISSUE THREAD

**Issue by JaneJeon** [pawelmalak/flame#215]
Hi, right now you can only have 4 columns, which, combined with the VERY wide padding on the main container, leads to bad UX on the desktop.

I can manually set the padding to zero, but I seemingly can't set the number of columns. Is there a way you could "dynamically" set the number of columns so that the columns try their best to fit the width of the parent container (so that, for example, you would still default to 4 when viewing from, say, a tablet, but can "expand" to 6 columns when viewing from a widescreen monitor)?

**Comment by pawelmalak** [comment]
You can achieve it with custom CSS and media queires. Here is the example on how to change [number of columns](https://github.com/pawelmalak/flame/wiki/Custom-CSS#change-number-of-columns-of-appilcation-grid-and-reduce-page-spacing) and [here](https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Media_queries#media_feature_rules) is more about CSS media queries.

**Comment by aarste** [comment]
That custom code unfortunately breaks mobile view, but this minor addition should fix it so that it only expands to 7 columns when the browser window is more than 900px width:

```
@media (min-width: 900px) {
.AppGrid_AppGrid__33iLW {
  grid-template-columns: repeat(7, 1fr) !important;
  }
}
```
