### ISSUE TITLE
[BUG] Cannot add any applications

### ISSUE THREAD

**Issue by siancu** [pawelmalak/flame#218]
**Deployment details:**
- App version [e.g. v1.7.4]: 2.0.1
- Platform [e.g. amd64, arm64, arm/v7]: amd64 (on Synology NAS)
- Docker image tag [e.g. latest, multiarch]: latest

---

**Bug description:**

After installing flame, on the homepage, it tells me that I don't have applications defined and that I can do so in /applications. However the /applications page is empty without any Add button (as I saw in some screenshots). 

You can see how the /applications page looks for me in the attached screenshot.

<img width="815" alt="Screenshot 2021-11-21 at 17 42 13" src="https://user-images.githubusercontent.com/39668/142770980-b78fd281-4b22-49fa-929f-8f0dc2f3e8b9.png">

**Comment by pawelmalak** [comment]
You need to be logged in first. Go to Settings > App and login from there. If you didn't change it, the default password is `flame_password`. 

I will have to change that message to make it clear.

**Comment by siancu** [comment]
Ah, ok, now I see. I will close the issue then because it is not a bug. But I agree with you, it is not very clear that one needs to login.
