### ISSUE TITLE
[BUG] Hostname and IP address deliver different dashboards

### ISSUE THREAD

**Issue by longdas** [pawelmalak/flame#219]
**Deployment details:**
- App version [e.g. v1.7.4]: 2.0.1
- Platform [e.g. amd64, arm64, arm/v7]: amd64 
- Docker image tag [e.g. latest, multiarch]: not set, I manually pull. 

---

**Bug description:**

I set up flame on the hostname assigned to my server, and set it to Firefox home page. Realized that having to resolve the hostname everytime slowed down the page loading, I set it to the IP:Port of the server. The version of Flame running on the IP:Port of the server was different than the one I have on the hostname, and the authentication password I set does not work. The categories and bookmarks are the same between the two versions. 

---

**Steps to reproduce:**

Give the server running flame a static IP and hostname through your router (DDWRT in my case)
Run flame in docker-compose
Configure flame to your liking on hostname:port and set a custom password
Go to ip:port and see authentication not work and different theme

I've also attached my compose file if it helps.

`
version: "3"                                                                                                            
 services:                                                                                                                 
   flame:                                                                                                                    
     image: pawelmalak/flame                                                                                                 
     container_name: flame                                                                                                   
     volumes:                                                                                                                  
        - /opt/flame:/app/data                                                                                                
     ports:                                                                                                                    
       - 5005:5005                                                                                                           
     environment:                                                                                                              
         - PASSWORD=key                                                                                       
     restart: unless-stopped           
`

**Comment by longdas** [comment]
Closing this, ID10T error. Vaultwarden was autofilling the wrong thing. Apologies.

**Comment by pawelmalak** [comment]
> Although the theme DID differ, so that could still be fixed

After you select theme it is saved in the browser localStorage associated with current page. From browser point of view, `ip:port` is different page then `hostname:port` and it doesn't have selected theme.

I suggest setting default theme for that.
