### ISSUE TITLE
[Feature Request] - Multiple devices docker integration

### ISSUE THREAD

**Issue by atropos112** [pawelmalak/flame#220]
Hello,
 
First of all, amazing job on v2, I felt v1 had few things missing and then v2 blew my mind, so much so that I had a realization that only one feature lacks from it being perfect in my use-case. 

My request is to allow multiple docker servers into Docker integration, the way I "imagine" it in the interface is to be able to write in `Settings->Docker->Docker host` something like `localhost; 192.168.1.105; <some-remote-ip>`. The person creating a feature request in #97 has shown interest in this as well, I presume this is what he was after in the first place actually.

Thank you for providing such amazing product.

**Comment by atropos112** [comment]
I checked the code a little bit (I do not know JavaScript or typescript  so pls verify what i wrote isn't garbage) and I feel that 

```

  // Get list of containers
  let hostList = hosts.split(';');
  for (const host in hostList) {
    try {
      if (host.includes('localhost')) {
        // Use default host
        let { data } = await axios.get(
          `http://${host}/containers/json?{"status":["running"]}`,
          {
            socketPath: '/var/run/docker.sock',
          }
        );

        containers = containers.concat(data);
      } else {
        // Use custom host
        let { data } = await axios.get(
          `http://${host}/containers/json?{"status":["running"]}`
        );

        containers = containers.concat(data);
      }
    } catch {
      logger.log(`Can't connect to the Docker API on ${host}`, 'ERROR');
    }
  }


```

In `controllers/apps/docker` might work, would make a pull request if not the fact that for me both the master branch and this method do not work with remote server as such I can't check.

**Comment by atropos112** [comment]
I don't mean to push, just wanted to know if there is any intention with doing anything of this sort or the idea is silly/niche and won't be pursued. Regardless of the answer thank you for such great product.

**Comment by atropos112** [comment]
The current build works for me now (for one server), I tried adjusting the code in useDocker file, but even changing the name of a single variable (everywhere) caused it to not work, its wizardry of some kind. I am giving up on this matter.

**Comment by Jeppedy** [comment]
Ditto here...  In my home lab, I use multiple hosts, each running Docker.  It would be very helpful to make this work for multiple Docker Hosts.

**Comment by jeffreyswiggins** [comment]
I also would love to have this feature.  I have been using Flame for over year (maybe 2 now) and have 3 (sometimes 4 with a DEV) Docker hosts and prefer to have them all in one "pane of glass page".  This has driven me over to the Homepage container recently.  I like this app better for its simplicity, but since that app supports multiple Docker Hosts, labels, etc, and this is singular unless you use the aforementioned db.sqlite hack (not going to do that) I have begun to move most of my stuff to it.

Appreciate the cleanliness and development you have put into this, just need this feature for me to use it full and further.
