### ISSUE TITLE
[BUG] Unable to select Customer Search Provider

### ISSUE THREAD

**Issue by zahidhanif** [pawelmalak/flame#228]
**Deployment details:**
- App version [e.g. v1.7.4]: 2.1.0
- Platform [e.g. amd64, arm64, arm/v7]: amd64
- Docker image tag [e.g. latest, multiarch]: latest

---

**Bug description:**

I have a custom search provider configured (Whoogle) but when I try and change the search on the search option on the Settings page, it selects Wikipedia instead of Google. I have tried restarting and recreating the container. I have also tried logging out and back in again.

---

**Steps to reproduce:**

1. Go to Settings | Search
2. Click on Default search provider drop down lost
3. Scroll down to Whoogle
4. Click Save changes

**Comment by pawelmalak** [comment]
What prefix are you using? Wikipedia is using `w` so you can't use it for your provider.

**Comment by zahidhanif** [comment]
I was using w but with the addition of Wikipedia, that must have caused an issue. Now that I have changed it, it's allowing me to save. Thanks for helping me fix it.
