### ISSUE TITLE
[BUG] Unable to connect to the database: SQLITE_ERROR: duplicate column name: orderId

### ISSUE THREAD

**Issue by Nelinski** [pawelmalak/flame#229]
**Deployment details:**
- App version [e.g. v1.7.4]: Just upgraded to 2.1.0 
- Platform [e.g. amd64, arm64, arm/v7]: Unraid/Docker
- Docker image tag [e.g. latest, multiarch]: Latest

---

**Bug description:**

Getting the following error when starting the docker container:

`[2021-11-26 20:55:34.893 UTC+0] [ERROR] Unable to connect to the database: SQLITE_ERROR: duplicate column name: orderId
`

The docker then stops.

---

**Steps to reproduce:**

Start the docker and check the logs.

**Comment by pawelmalak** [comment]
> Start the docker and check the logs.

I have 5 instances on 3 different platforms and all of them updated fine to 2.1.0.

Can you:
- Download [DB Browser for SQLite](https://sqlitebrowser.org/) and open your database file
- Modify `bookmarks` table by removing `orderId` column
- Restart the container and check if it fixed it?

![image](https://user-images.githubusercontent.com/24780509/143656056-ee6f7f1d-c49d-4c4f-a77c-6e2b273ac224.png)

**Comment by Nelinski** [comment]
Seems to be working OK now thanks.
