### ISSUE TITLE
[Feature Request] Multiuser

### ISSUE THREAD

**Issue by nomandera** [pawelmalak/flame#231]
I have ported to flame and it is excellent.

The request/question I have is if multuser support is on the roadmap?

Being the portal to my home it is not ideal that my extended family (including small children) see links to backoffice stuff.

At some point I will need to curate these links for them, I will have no choice and I am hoping this is something flame is working towards.

**Comment by vp-lab** [comment]
It'll would be nice to have multi-user and each user can see something.
You can create another container with flame and use only for kids atm.

**Comment by pawelmalak** [comment]
No, support for multiple users is not planned. I thought of it when implementing authentication but decided to go with a single admin user.
