### ISSUE TITLE
[BUG] Changes only apply after hitting F5.

### ISSUE THREAD

**Issue by catalinchertes** [pawelmalak/flame#236]
**Deployment details:**
- App version: latest (no docker)

---

**Bug description:**
When applying changes (ordering apps, changing config settings, etc..), they only update on the browser where the changes were made and so the other users that had the site open on another device/browser, need to hit F5 before the new changes are applied. It would be interesting for this changes to take effect for everyone with the page open in the browser without the need to refresh.

---

**Steps to reproduce:**

1. Open two instances of the app on different browsers.
2. Apply any change, like for example changing the apps order or changing the greet messages.
3. Check the changes being applied only on the browser where the changes were made. Hit F5 in the other browser to see changes take place.

**Comment by catalinchertes** [comment]
I would say this is a follow up on the #29 issue... settings now indeed update between devices, but you need to refresh them everytime.

**Comment by pawelmalak** [comment]
I don't really see any practical use of this. You would still need to refresh to get new CSS, apps, bookmarks etc.

**Comment by catalinchertes** [comment]
ok
