### ISSUE TITLE
[BUG] Unable to edit bookmarks

### ISSUE THREAD

**Issue by RmigD** [pawelmalak/flame#239]
**Deployment details:**
- App version [e.g. v1.7.4]: 2.1.0
- Platform [e.g. amd64, arm64, arm/v7]: amd64
- Docker image tag [e.g. latest, multiarch]: pawelmalak/flame latest

---

**Bug description:**
After updating to the latest version, I am unable to edit bookmarks. I expected to see a list of bookmarks and edit buttons, but I see a single string "Switch to grid view and click on the name of category you want to edit". No idea what this grid is.
---

**Steps to reproduce:**

1. Go to homepage
2. Click on Bookmarks
3. Click on "Edit bookmarks" 
![flame](https://user-images.githubusercontent.com/31237907/144328770-76a3c2b8-0613-4505-a56f-8a8e5fc1ce94.png)

Just before submitting this, I found a way to edit, but it doesn't seem right.... I go into "edit categories", I click the pencil icon, I close the popup that shows up. I can then go into "edit bookmarks" and see the bookmarks that belong to the category I clicked on before. This doesn't seem very intuitive or efficient. I will submit this ticket just the same, but feel free to close it...

**Comment by pawelmalak** [comment]
Just click on "edit bookmarks" again and it will change view to grid mode. Then just click on category name you want to edit.

**Comment by RmigD** [comment]
Clicking "edit Bookmarks" twice and then clicking on the name of the category to which the bookmark is assigned works. I would do this differently. I would not require a second click in "edit Bookmarks" and I would skip the clicking on the category. So when clicking "edit Bookmarks", just show all of them. Isn't this what it was like before?

**Comment by pawelmalak** [comment]
It was, but to implement option to set custom order for bookmarks it had to be changed.

**Comment by pawelmalak** [comment]
It was, but it had to be changed to implement option to set custom order for bookmarks.

**Comment by ctrpch** [comment]
> **Deployment details:**
> 
>     * App version [e.g. v1.7.4]: 2.1.0
> 
>     * Platform [e.g. amd64, arm64, arm/v7]: amd64
> 
>     * Docker image tag [e.g. latest, multiarch]: pawelmalak/flame latest
> 
> 
> ## **Bug description:**
> After updating to the latest version, I am unable to edit bookmarks. I expected to see a list of bookmarks and edit buttons, but I see a single string "Switch to grid view and click on the name of category you want to edit". No idea what this grid is.
> 
> **Steps to reproduce:**
> 
>     1. Go to homepage
> 
>     2. Click on Bookmarks
> 
>     3. Click on "Edit bookmarks"
>        ![flame](https://user-images.githubusercontent.com/31237907/144328770-76a3c2b8-0613-4505-a56f-8a8e5fc1ce94.png)
> 
> 
> Just before submitting this, I found a way to edit, but it doesn't seem right.... I go into "edit categories", I click the pencil icon, I close the popup that shows up. I can then go into "edit bookmarks" and see the bookmarks that belong to the category I clicked on before. This doesn't seem very intuitive or efficient. I will submit this ticket just the same, but feel free to close it...

I had the same issue and this work-around did allow me to edit the bookmarks
