### ISSUE TITLE
[BUG] Custom Greetings is no work anymore

### ISSUE THREAD

**Issue by mariushosting** [pawelmalak/flame#245]
When I add custom Greetings is no works anymore since version 2.1
Nothing is show on the home.

**Comment by pawelmalak** [comment]
It works fine for me. Can you show me your config file?

**Comment by mariushosting** [comment]
Sure here you go: https://mariushosting.synology.me/sharing/aAOHz8pg5

**Comment by pawelmalak** [comment]
```json
"greetingsSchema": "mariushosting",
```

You need to have 4 values here. So if you want it to always show "mariushosting" it needs to be `mariushosting;mariushosting;mariushosting;mariushosting`

**Comment by mariushosting** [comment]
Thanks for the input!
