### ISSUE TITLE
[BUG] Unable to delete a bookmark

### ISSUE THREAD

**Issue by N0Klu3** [pawelmalak/flame#247]
**Deployment details:**
- App version [e.g. v1.7.4]: 2.1.1
- Platform [e.g. amd64, arm64, arm/v7]:  docker
- Docker image tag [e.g. latest, multiarch]:  latest

---

**Bug description:**

Unable to delete a bookmark.
Click the trashcan, it says to confirm, I confirm and then nothing it still remains.
---

**Steps to reproduce:**
Click the trashcan, it says to confirm, I confirm and then nothing it still remains.

**Comment by pawelmalak** [comment]
Are you getting any errors in the browser console or in the container logs? Is the bookmark still there after refreshing the page?

**Comment by N0Klu3** [comment]
@pawelmalak refreshing the bookmark is still there.
Looked in docker no errors.
And no errors pop up when deleting it. The warning pops up, click Ok, it disappears and bookmark is still there.

No idea but just tried it yet again to make sure for you and it deleted... sigh.
I'll close this now, thanks for the reply tho really appreciate it.
