### ISSUE TITLE
Update Flame - without Docker

### ISSUE THREAD

**Issue by user551871823** [pawelmalak/flame#264]
Hi. 
I followed your Guide "Installation without Docker". 
How do I update this kind of Installation. 
An other option would to give an export option for my configuration (Apps, Bookmarks,...) :-)
Regards Stephan

**Comment by pawelmalak** [comment]
You just pull new code with `git pull` and start it as before.

**Comment by user551871823** [comment]
Ok. Needed to do some research to understand. 
"git fetch --all && git reset --hard origin/master" solved my problem. 
The ".env" file should be saved and restored afterwards.
Maybe you could add a hint to the installation guide.
Regards and thx for the great work!!
