### ISSUE TITLE
Settings are missing

### ISSUE THREAD

**Issue by Socos21** [pawelmalak/flame#267]
Hello everyone,

I updated to 2.2.0 version and now I lost lots of options from the settings(bottom left cog).
Basically the only thing I can see on settings are Theme and App.  
Any idea what I could try in order to make them appear again?

**Comment by pawelmalak** [comment]
Are you logged in?

**Comment by Socos21** [comment]
> Are you logged in?

OMG! I feel so stupid now. I never set up a password to login and it work straight away as soon as installed it on docker. 
I set up a password, I logged in and it work!

Thanks so much for your help!
