### ISSUE TITLE
[BUG] Local Search open in same tab does not work when pressing enter on keyboard

### ISSUE THREAD

**Issue by redsx16** [pawelmalak/flame#270]
**Deployment details:**
- App version [e.g. v1.7.4]: 2.2.0
- Platform [e.g. amd64, arm64, arm/v7]: 
- Docker image tag [e.g. latest, multiarch]: latest

---

**Bug description:**

When searching for an app with local search and pressing enter the setting to open in the same tab does not work. If the user clicks on the app it will open in the same tab.

---

**Steps to reproduce:**

1. Set Search Default provider to 'Local Search'
2. Set Open search results in the same tab to 'True'
3. Save
4. Search for a local application and press enter (app opens in a new tab)
5. Repeat step 4 but instead click on the app (app opens in the same tab)

**Comment by pmjklemm** [comment]
There is a workaround: just set the search provider (settings > search) to anything but local.

**Comment by TheAnachronism** [comment]
> There is a workaround: just set the search provider (settings > search) to anything but local.
Yeah, but this makes the search usage for applications / bookmarks unusable.

**Comment by rcdailey** [comment]
When are we getting a fix for this?

**Comment by sn0am** [comment]
This issue still seems to be there. I built an image from the latest files and search in same tab still opens a new tab every time.
