### ISSUE TITLE
[New Feature] Hide or edit the greeting

### ISSUE THREAD

**Issue by gitcatpeter** [pawelmalak/flame#28]
"Good morning or evening" takes a bit too much screen for my taste.
Would it be possible to edit it or hide it completely?

**Comment by pawelmalak** [comment]
What about weather module then? Should it be visible only when greeting is visible too?

**Comment by gitcatpeter** [comment]
> What about weather module then? Should it be visible only when greeting is visible too?

I think so, unless there is a way to still fit the weather somewhere.
