### ISSUE TITLE
[INFO] are there some sort of APIs, or similar way, to automate creation of entries?

### ISSUE THREAD

**Issue by posta246** [pawelmalak/flame#294]
Hi,
I'm looking for a dashboard that allows me to insert entries or add bookmarks etc via bash scripts, so when a new services is deployed, the related link is shown into the dashboard itself. Can it be done with flame? How? Hope yes, flame is a super cool dashboard!
thanks a lot!

**Comment by pawelmalak** [comment]
Flame is using REST Api for all of its resources. It's not well documented since it's only for internal usage.

For example, to create new app:
```plaintext
method: POST
path: https://flame.tld/api/apps
headers:
  - Authorization-Flame: Bearer <<TOKEN>>
body:
  - name : String : required
  - url : String : required
  - icon : String : optional
  - description : String : optional
```

And to get auth token:
```plaintext
method: POST
path: https://flame.tld/api/auth
body:
  - password : String : required
  - duration : String : required
```
