### ISSUE TITLE
Feature Request: Always Search External on Enter

### ISSUE THREAD

**Issue by josheinstein** [pawelmalak/flame#295]
I like to have local search be the default, without a prefix, so as I type, local results are shown. However, when I press enter, it would be nice to have that automatically break out to an external default search provider (i.e. Google) without having to use a prefix.

It seems to be hard coded to use DuckDuckGo when local search is the default.

Have not used React/Typescript before, but I will give it a shot. Figured I'd put this here anyway in case it's helpful to others.

**Comment by dannyhanes** [comment]
This would be super helpful. I want local search for everything, but if nothing is found and I press enter, I want to search Google instead of DuckDuckGo.

**Comment by TheAnachronism** [comment]
Could the implementation of this, resulted in this (https://github.com/pawelmalak/flame/issues/270) bug?
