### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by EVIL-Teken** [pawelmalak/flame#299]
**Deployment details:**
- App version: v2.2.1 
- Platform: arm/v7 
- Docker image tag: multiarch 

---

**Bug description:**

Custom Greeting: The system will accept the custom greeting and save fine. The system will randomly display the message but more often than not that message isn't seen at all. This message display issue is seen on all operating systems and web browsers spanning Windows 7, Windows 10, Ubuntu 20.X, Raspbian Bullseye, iPhone 10, and various other iOS / Android devices.

Web Browsers tested with the same display issue: Chrome, Edge, Safari, Fire Fox, IE . . .

---

**Steps to reproduce:**

This bug is always present and haven't found a way to force the custom message to appear. Have tried to clear all the web cache, history, cookies, etc. Have rebooted all of the computers and the problem persists. The Docker container and the application has been hard stopped, killed, restarted, and the problem continues to persist.

**Comment by pawelmalak** [comment]
Can you show your config file?

**Comment by EVIL-Teken** [comment]
Sure listed below and thank you!
============
============

version: '2.1'
services:
  flame:
    image: pawelmalak/flame:latest
    container_name: flame
    volumes:
      - <host_dir>:/app/data
      - /var/run/docker.sock:/var/run/docker.sock # optional but required for Docker integration feature
    ports:
      - 5005:5005
    environment:
      - PASSWORD=flame_password
    restart: unless-stopped

**Comment by pawelmalak** [comment]
This is your docker-compose file. What I meant is your app config. You can get it from your mounted directory: `host_dir/config.json` or your `flame.instance.com/api/config`

**Comment by EVIL-Teken** [comment]
I've looked everywhere I can't locate either of these config files in Portainer / root of the RPI OS?

**Comment by pawelmalak** [comment]
```yml
container_name: flame
volumes:
  - <host_dir>:/app/data
```

`<host_dir>` is where you mounting your flame data directory. Or just open your flame instance in the browser and add `/api/config` to the url

**Comment by EVIL-Teken** [comment]
Appreciate the guidance to find the information and removed some of the user data:

{"success":true,"data":{"WEATHER_API_KEY":"48222201","lat":,"long":,"isCelsius":true,"customTitle":"SENTINEL - SYSTEM - MONITOR ","pinAppsByDefault":true,"pinCategoriesByDefault":true,
"hideHeader":false,"useOrdering":"orderId","appsSameTab":false,"bookmarksSameTab":false,"searchSameTab":false,"hideApps":false,"hideCategories":false,"hideSearch":false,
"defaultSearchProvider":"l","dockerApps":false,"dockerHost":"localhost","kubernetesApps":false,"unpinStoppedApps":false,"useAmericanDate":true,"disableAutofocus":false,
"greetingsSchema":"SENTINEL - SYSTEM - MONITOR","daySchema":"Sunday;Monday;Tuesday;Wednesday;Thursday;Friday;Saturday","monthSchema":"January;February;March;April;May;June;July;August;September;October;November;December","showTime":true,
"defaultTheme":"tron","isKilometer":true,"weatherData":"humidity","hideDate":false}}

**Comment by pawelmalak** [comment]
```json
"greetingsSchema":"SENTINEL - SYSTEM - MONITOR",
```

You only have one greetings message set, so it will be only visible from 6pm to 12pm.

You need to have all four messages set for this feature to work correctly, so you have to set it like that:
`SENTINEL - SYSTEM - MONITOR;SENTINEL - SYSTEM - MONITOR;SENTINEL - SYSTEM - MONITOR;SENTINEL - SYSTEM - MONITOR`

![image](https://user-images.githubusercontent.com/24780509/151082848-60482f3c-b2bd-4f69-bfcf-3585f616eaf7.png)

**Comment by EVIL-Teken** [comment]
Resolved - Thank You!
