### ISSUE TITLE
Instructions to install without the need for docker

### ISSUE THREAD

**Issue by ithakaa** [pawelmalak/flame#30]
Do we have any installation document on installing without docker?

**Comment by ithakaa** [comment]
No?

**Comment by rgriffogoes** [comment]
Not really an answer, but as the Dockerfile is there, you can see all steps required to build from source, and how to run it.

For node, you will probably use something like pm2

**Comment by ithakaa** [comment]
Dockerfile isn't very helpful

Thanks anyway

**Comment by pawelmalak** [comment]
### Prerequisites
You need to have `git` and `Node.js` installed on your system.

### Downloading source code
```sh
git clone https://github.com/pawelmalak/flame
cd flame

# installing dependencies (it might take some time)
npm run dev-init
```

### Building client
```sh
cd client
npm run build
```

Then create `data` and `public` directories in root directory of the project. Move all content of `client/build` to `public` directory.

### Running
Edit `.env` file in root directory - change `NODE_ENV` variable to:
```sh
NODE_ENV=production
```

Start Flame with:
```sh
node server.js
```

Wait till server starts. You should get following logs in the terminal:
```sh
Socket: listen
Server is running on port 5005 in production mode
Connected to database
All models were synced
Initial config created
```

Flame is now running. Visit it at `localhost:5005`

**Comment by ithakaa** [comment]
thank you so much, it worked perfectly. !!!

**Comment by pawelmalak** [comment]
Glad it worked. Added installation guide to the wiki and updated README.md with link to it.
