### ISSUE TITLE
Docker image for ARM7

### ISSUE THREAD

**Issue by akhilrex** [pawelmalak/flame#31]
Any plans for building a docker image for ARM7 so that this can be setup on Raspberry Pi. I know I can build from source on that but having an official image would be nice.

**Comment by pawelmalak** [comment]
I build image for linux/arm/v7 but I don't have any device with that architecture so I can't test if it works.
If you want, you can test it by pulling `pawelmalak/flame:dev_arm` from Docker Hub.

**Comment by Ajaymamtora** [comment]
Doesnt work for me, ubuntu 20.04, pi 4B

**Comment by pawelmalak** [comment]
It worked on mine - RPi 4B Raspberry Pi OS (64 bit). What errors are you getting?

**Comment by akhilrex** [comment]
I have the same setup as Ajay. I'll try and let you know.

Checkout out the build process in any of my projects - Podgrab or Hammond.
It creates multi platform build easily.

Thanks and Regards

Akhil Gupta

**Comment by Ajaymamtora** [comment]
Thanks it works fine now with the latest docker compose + multi arch tag
