### ISSUE TITLE
[Feature request] add SSL support

### ISSUE THREAD

**Issue by barabasz** [pawelmalak/flame#319]
At least some basic support for SSL like uploading X.509 certificate (cert.pem) and private key (in the same way as Portainer does) and options to enable SSL (and HSTS - why not?).

**Comment by nomandera** [comment]
Most users in the space use reverse proxy via SWAG or some other project which have a strong focus on SSL/TLS.

This removes the user burden on maintaining lots of disparate TLS setups and project burden completely.

Obviously it is not the perfect solution for "all things" but if you can go this route you may end up liking it.

**Comment by spiralham** [comment]
I second the recommendation by @nomandera , setting up a reverse proxy removes the burden of proper encryption configuration from both developers _and_ users alike.  I use nginx with a wildcard cert which allows me to put any self-hosted project behind SSL effortlessly.

**Comment by barabasz** [comment]
@nomandera & @spiralham - thank you!
I set up nginxproxymanager.com - and it works (and looks) great!
