### ISSUE TITLE
[BUG] Unable to change weather icon color

### ISSUE THREAD

**Issue by CobreDev** [pawelmalak/flame#320]
**Deployment details:**
- App version [e.g. v1.7.4]: 2.2.1
- Platform [e.g. amd64, arm64, arm/v7]: amd64
- Docker image tag [e.g. latest, multiarch]: latest

---

**Bug description:**

I'm able to use custom CSS to change the Primary, Accent, and Background colors of everything *except* the weather icon. My custom css is as follows:

```
body {
--color-primary: #ddd!important;
--color-accent: #e5a00d!important;
--color-background: #1f2326!important;
}
```

I've used Safari, Chrome, and Firefox and the issue is present in all of them
---

**Steps to reproduce:**

1. Set up Weather integration
2. Use custom CSS to change Primary and Accent colors
3. Observe the default aqua color of the weather icon

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/36574329/155856124-40529cd7-2b5a-481d-b407-c7003befef07.png">

**Comment by pawelmalak** [comment]
Technically it's not a bug since [wiki](https://github.com/pawelmalak/flame/wiki/Custom-theme-with-CSS) clearly states that

> icon color will not be affected

when using custom CSS.

It will be changed with #246 when custom theme can be created directly in the app, without writing custom CSS

**Comment by CobreDev** [comment]
Oops, somehow I missed that sentence. Looking forward to it!
