### ISSUE TITLE
[BUG] Create Bookmark Auto Closes on URL Select

### ISSUE THREAD

**Issue by sankethguru** [pawelmalak/flame#330]
**Deployment details:**
- App version [e.g. v1.7.4]: 2.2.1
- Platform [e.g. amd64, arm64, arm/v7]: amd64/proxmox/openmediavault/docker
- Docker image tag [e.g. latest, multiarch]: latest

---

**Bug description:**

On creation of bookmark, after entering all the fields, selecting the URL field contents via mouse from end to beginning will close the new bookmark creation frame. Can only tab into Bookmark URL field from Bookmark Name. 

---

**Steps to reproduce:**

1. Click on add bookmark.
2. Enter all fields.
3. Select bookmark URL from right to left. (selecting from left to right does not cause this issue!).
4. Add bookmark frame closes by itself.

**Comment by pawelmalak** [comment]
It's not a bug. You can close modal by clicking either 'X' button or anywhere outside the modal. When you are selecting text, you are dragging mouse cursor outside the modal area and releasing it there which causes modal to close.

Try keeping cursor inside the modal when selecting text or just select it by double-clicking on the input filed.
