### ISSUE TITLE
[BUG] Adding an aplication with just spaces in all the feilds causes all page elements to disapear

### ISSUE THREAD

**Issue by sbavila** [pawelmalak/flame#332]
Adding a empy app record break the dashboard

Steps to Recreate
1. Add new app record with a [space] as the only character in all the required feilds.
2. Refresh

System Info
Flame 2.2.2
Docker 

I was trying to add an empty app bookmark so that i could create an empty space. The form accepted my entry and made a new application link but on reload the whole dashboard is now just an empty page. 

Head to [home.sba.video](http://home.sba.video) to have a look. 

Is there a way of recovering? 

Could it be a new feature to add a "spacer" to help organise everything?

Thanks,

Salvador

**Comment by pawelmalak** [comment]
> Is there a way of recovering?

You will need to open database file and remove faulty entry.

Which app version are you using and what exactly did you type into the form?

**Comment by sbavila** [comment]
I added the relevant info whilst you were comenting I think.

> Adding a empy app record break the dashboard
> 
> Steps to Recreate
> 
>     1. Add new app record with a [space] as the only character in all the required feilds.
> 
>     2. Refresh
> 
> 
> System Info Flame 2.2.2 Docker

**Comment by pawelmalak** [comment]
Right now, empty entries are not supported. To fix your instance, you need to:
- download [DB Browser for SQLite](https://sqlitebrowser.org/) and open `db.sqlite` file with it
- go to `apps` table, delete faulty app and write changes

This issue will be dedicated to fixing the `empty page` bug

**Comment by sbavila** [comment]
Thanks - deleting the entry fixed it. Thanks.
