### ISSUE TITLE
[BUG] Unable to change the theme with new version 2.3.0

### ISSUE THREAD

**Issue by iAmSaugata** [pawelmalak/flame#335]
**Deployment details:**
- App version [e.g. v1.7.4]: 2.3.0
- Platform [e.g. amd64, arm64, arm/v7]: arm64
- Docker image tag [e.g. latest, multiarch]: pawelmalak/flame:multiarch2.3.0

---

**Bug description:**

In the theme panel, selecting different theme is not work, it is not registering the click.

---

**Steps to reproduce:**

1. Go to '...' Settings
2. Click on '....' Theme
3. Scroll down to '....' Now under App themes, try selecting any theme.

I am using latest MS Edge browser, earlier version (v2.2.2) it was working fine.

**Comment by iAmSaugata** [comment]
It is with NGINX Proxy cache. issue resolved.

**Comment by iAmSaugata** [comment]
@warmbo I just disabled the cache in the Nginx Reverse Proxy, if you already have that disabled, then i would suggest to check it from In-Private browsing, if you still having the issue, the delete the host entry in Nginx reverse Proxy and create new one.

If you are using this with cloudflare proxy, you have to create that too.

**Comment by warmbo** [comment]
@iAmSaugata I'm just trying to use it locally, no proxy, and have same issue. Thanks for the help though!
