### ISSUE TITLE
[DOCUMENTATION] - Change number of columns of BOOKMARK Grid

### ISSUE THREAD

**Issue by carlosdurante** [pawelmalak/flame#344]
Hello, and congratulations on a job well done! This app is one of my favorites.
I'm trying to figure out a similar way to create a custom CSS to make my Bookmarks have more columns, similar to the Applications session. I found the instructions for Application in the documentation, but not for Bookmarks.
Is there anyone who knows how to do it?

Example of Application:
.AppGrid_AppGrid__33iLW {
  grid-template-columns: repeat(7, 1fr) !important;
}

**Comment by gitcatpeter** [comment]
.BookmarkGrid_BookmarkGrid__26LlR {
  grid-template-columns: repeat(8, 1fr) !important;
}

**Comment by carlosdurante** [comment]
> 

It worked!
Thank you very much! 

How did you figure out that number "__26LlR"?

**Comment by carlosdurante** [comment]
Got it! thank you for your support!
