### ISSUE TITLE
[BUG] Custom title not shown anywhere

### ISSUE THREAD

**Issue by zilexa** [pawelmalak/flame#352]
**Deployment details:**
- App version [2.3.0]: 
- Platform [amd64, Manjaro Linux host, Docker Compose]: 
- Docker image tag [none, so latest is used?]: 

---

**Bug description:**

I have set a custom title via Settings, but it is not shown anywhere. 
I do see the greeting, I can disable the greeting but still the custom title is not shown. Tested mostly on mobile devices.

---

**Steps to reproduce:**

1. Go to Settings > Interface 
2. Set a custom page title
3. Hit save, go back and try to find it anywhere.

**Comment by supermamon** [comment]
The custom page title setting is the title that appears on the browser tab, not the page itself. If you're using Safari, you won't see this.
