### ISSUE TITLE
[Feature] Default app visibility

### ISSUE THREAD

**Issue by Xosten** [pawelmalak/flame#366]
Hey,

I'm using flame since a few months and love the minimalistic UI. I couldn't find the option to set the default visibility for Applications. I guess the feature isn't implemented yet. Is it possible to have something like this in the near future, please?

Thanks again for the awesome dashboard!
Cheers,

**Comment by kevjustice** [comment]
YES!  This is sorely needed - a setting so that  all new items default to hidden.

**Comment by Xosten** [comment]
Stalled since a year, closing for now
