### ISSUE TITLE
Get Flame to open as a standalone window in Brave/Chrome on Android.

### ISSUE THREAD

**Issue by squidds** [pawelmalak/flame#374]
Flame does not open as a standalone window when I create a shortcut for it in Brave Browser. It's not a huge issue, but would definitely improve QOL on Android. It works on other dash applications, and it's nice because you can hit the X  at the top left after opening one of your  applications to return back to the dashboard. 
![Screenshot_20220621-195417](https://user-images.githubusercontent.com/64927214/174915720-dab8e0bf-0261-4691-ab97-832940558d35.png)
![Screenshot_20220621-193742~2](https://user-images.githubusercontent.com/64927214/174915765-efc0dfaf-51ea-49d3-beac-39c4b60485ec.png)

As an example here is what Adguard looks like when you add it to home screen. No address bar, opens as a separate application from brave/chrome. 

![Screenshot_20220621-200104](https://user-images.githubusercontent.com/64927214/174915906-f58d9d2d-6b29-4242-a161-edceda145116.png)

**Comment by Lissy93** [comment]
That functionality is called a Progressive Web App / [PWA](https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps).

It can be implemented quite easily, just by adding a [Web Manifest](https://developer.mozilla.org/en-US/docs/Web/Manifest) file, and importing it in the [`index.html`](https://github.com/pawelmalak/flame/blob/master/client/public/index.html#L6).
While your there, those icons which are currently in the head tag can also be moved to the manifest.

**Comment by squidds** [comment]
> That functionality is called a Progressive Web App / [PWA](https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps).
> 
> It can be implemented quite easily, just by adding a [Web Manifest](https://developer.mozilla.org/en-US/docs/Web/Manifest) file, and importing it in the [`index.html`](https://github.com/pawelmalak/flame/blob/master/client/public/index.html#L6). While your there, those icons which are currently in the head tag can also be moved to the manifest.

oh cool, thank you. very much!
