### ISSUE TITLE
WeatherAPI API request failed

### ISSUE THREAD

**Issue by sderuiter** [pawelmalak/flame#39]
Hi,

I keep getting API request failed when saving the WeatherAPI settings. 
However, when using the url from:
https://github.com/pawelmalak/flame/blob/1636b705de05e620cf7f5636a8b29cfd9aaebad5/utils/getExternalWeather.js#L24
with my key and lat & long in a browser, *does* lead to a valid response. 

Not sure where to look further?

**Comment by pawelmalak** [comment]
Are you getting:
- browser console: `GET https://flame.host.tld/api/weather/update 500`
- docker logs: `Error: External API request failed` ?

**Comment by sderuiter** [comment]
I'm getting:
`GEThttps://sprocker.nl/api/weather/update
[HTTP/2 500 Internal Server Error 19ms]` in console and

`External API request failed` in docker logs.

**Comment by pawelmalak** [comment]
I'm not able to reproduce this issue on any of flame instances I'm running. I've created special docker image with more verbose logging in `getExternalWeather.js`. You can try it with `docker pull pawelmalak/flame:dev`

**Comment by sderuiter** [comment]
I've used your dev tag, however I do not see any additional logs.
I didn't mention the environment I'm running this in...
It's running on Unraid, with NginxProxyManager and Authelia protecting it all. NPM is pointing the domain.tld (no subdomain) to the flame container (protected by a SSL certificate). 

My guess is that my Authelia config is somehow preventing the update from happening? 
However, looking at the network traffic, I can't figure what I should unblock to give Flame the appropriate access.

My current configuration.yml looks like:
`
```
rules:
- domain: domain.tld
      policy: one_factor
```
`

**Comment by pawelmalak** [comment]
I'm also hosting it on Unraid with NginxProxyManager but without Authelia and it's working fine. Are you getting the same error while accessing it with ip:port instead of domain.tld?

**Comment by sderuiter** [comment]
I just tried it again on Unraid_IP:5030 and get the same error.

**Comment by pawelmalak** [comment]
I've created another `:dev` tag. If it also won't log anything I don't think I'll be able to help with this issue.

**Comment by sderuiter** [comment]
Well, I don't know what has changed, but I restarted the container from the :dev tag and Weather now works, for for unraid_ip as well as the domain.tld!
 
Thanks.

**Comment by pawelmalak** [comment]
That's weird because the only difference between `:latest` and `':dev` tags are some additional console.logs. All other logic was untouched.
