### ISSUE TITLE
Longitude / Latitude not working

### ISSUE THREAD

**Issue by jbeck22** [pawelmalak/flame#40]
Using the long/lat data from latlong.net as instructed, Flame will not accept **any** value in the "location latitude" field.  Errors is "Enter a valid value"

**Comment by pawelmalak** [comment]
Which browser are you using?

**Comment by jbeck22** [comment]
Safari 14.1.1

MacOS BigSur

**Comment by jbeck22** [comment]
![Screen Shot 2021-06-16 at 4 43 48 PM](https://user-images.githubusercontent.com/4844115/122290954-4619b800-cec2-11eb-91b6-b1784f0b648a.png)

**Comment by jbeck22** [comment]
Just tried Chrome and it worked 100%.  Refreshed in Safari and it also shows weather data now. 


You can close this out, but you might want to take a peek at the code to what is causing this and or update your instructions for this use case.

Thanks!

**Comment by pawelmalak** [comment]
I stumbled upon the same issue on my iPhone yesterday and suspected it might be related to Safari WebKit. I'll take a closer look at it.
