### ISSUE TITLE
How to set a local image as the background?

### ISSUE THREAD

**Issue by justsonghua** [pawelmalak/flame#415]
I deploy this container on unraid docker. And create a path /images links to /mnt/user/support/theme in the container setting. Then I put the image into the theme folder and set it in the css as follows. 

body { 
  background: 
    linear-gradient( rgba(0,0,0,0.3), rgba(0, 0, 0, 0.3) ),
    url('/images/1.jpg') no-repeat center fixed;
    background-size: cover;
}

But the picture has not been loaded, and the background is still gray. I don't know much about the relevant css settings, so I asked my friends to help me fix it but didn't work. So can someone help me?

**Comment by aadityadhruv** [comment]
Here's what I ended up doing:

I made a directory on my host to store all the backgrounds called `backgrounds`. This was mounted to `/app/public/backgrounds/` and then I simply referenced the image in the custom CSS as `backgrounds/<wallpaper>.png`. Hope this helps!

**Comment by justsonghua** [comment]
> Here's what I ended up doing:
> 
> I made a directory on my host to store all the backgrounds called `backgrounds`. This was mounted to `/app/public/backgrounds/` and then I simply referenced the image in the custom CSS as `backgrounds/<wallpaper>.png`. Hope this helps!

 I tried this way, but it didn't work for me. So I direct store my background photos in `/appdata/flame/uploads`. Then in the CSS use the follow path `./uploads/images/wallhaven-eo19ro.png`. And it works.
