### ISSUE TITLE
Sort bookmarks

### ISSUE THREAD

**Issue by vp-lab** [pawelmalak/flame#43]
It'll be nice if you could drag'n'drop the order of bookmarks like on the bookmarks category or applications.

**Comment by gitcatpeter** [comment]
Agree. Excellent work on drag and drop in other sections though.

**Comment by ValentinPifu** [comment]
Can you fix this in 1.5? It's almost perfect for me.

**Comment by pawelmalak** [comment]
Unlikely. Bookmarks are processed different than apps and categories so it would probably require complete redesign of how bookmarks are handled on the client side.

**Comment by ValentinPifu** [comment]
Ok that's fine.
One more request: can you add a button in settings -> Other -> Hide bookmarks? I'll use only apps to arrange them how I want, but I don't want to see the this:
```
BOOKMARKS
You don't have any bookmarks. You can add a new one from /bookmarks menu
```

**Comment by pawelmalak** [comment]
Yes. You can open a new issue for this so I won't forget about it and it should be out with v1.5.
