### ISSUE TITLE
Lock/Hide items behind authentication

### ISSUE THREAD

**Issue by pawelmalak** [pawelmalak/flame#45]
This could be implemented with #33. 

The main idea is to add new property to apps, categories and bookmarks which would hide them if user is not authenticated. That way we could still provide guest access to certain set of items while require authentication for the rest.

**Comment by Jules-WinnfieldX** [comment]
The ability to lock settings behind authentication would also make for a great upgrade.

**Comment by opiumcloud** [comment]
I've managed to lock /applications and /bookmarks trough nginx, but /settings is still accessible trough the main page. This would be a nice addition for me too.

**Comment by AzamServer** [comment]
+1

**Comment by mariushosting** [comment]
+1

**Comment by amberflag48** [comment]
+1

**Comment by kevingruesser** [comment]
+1

**Comment by AzamServer** [comment]
Any ETA on this feature?

**Comment by pawelmalak** [comment]
Hopefully next week. I have been working on it past two weeks and everything is almost ready. Just need to test it and fix some bugs.

![image](https://user-images.githubusercontent.com/24780509/141614482-4810f332-2117-4d35-a80f-d67a0de46679.png)
