### ISSUE TITLE
Some help on a custom CSS please.

### ISSUE THREAD

**Issue by gitcatpeter** [pawelmalak/flame#50]
Any pointers for those that don't know anything about it please?
Any samples?
For instance how to change number of columns on the screen or widen the whole usable area.

Much appreciated!

**Comment by pawelmalak** [comment]
[Custom CSS](https://github.com/pawelmalak/flame/wiki/Custom-CSS)

**Comment by gitcatpeter** [comment]
I used this example - Change number of columns of Appilcation Grid and reduce page spacing
The app starts to use the whole screen as needed, but number of visible columns remains the same i.e. 4 
It seems the columns width increases too and clicking on the far right of an item (which looks like an empty screen) invokes the that app. That suggest the app/bookmark "button" is extended all the way to the right.

Maybe something else needs to be included in that CSS example for it to work.

**Comment by pawelmalak** [comment]
> The app starts to use the whole screen as needed, but number of visible columns remains the same i.e. 4

Weird. I used the same code from wiki and it works:

https://user-images.githubusercontent.com/24780509/123396447-9c14ec80-d5a1-11eb-8472-363d3106a61d.mp4

**Comment by pawelmalak** [comment]
> The app starts to use the whole screen as needed, but number of visible columns remains the same i.e. 4

Weird. I used the same code and it works:

https://user-images.githubusercontent.com/24780509/123405856-8a841280-d5aa-11eb-94a8-9343a8d947f2.mp4

**Comment by gitcatpeter** [comment]
OK, I know what the problem is. Does your CSS snippet works for Apps only and not to bookmarks (bookmarks requiring another CSS code?)?

I have turned Apps OFF and have everything under Bookmarks (because there are no Categories for Apps and I want my links grouped anyway).
Apparently the CSS does not apply to Bookmarks-only section or it's a bug.

**Comment by pawelmalak** [comment]
Yes, that code was for AppGrid only. For categories you would probably go with:
```css
.BookmarkGrid_BookmarkGrid__26LlR {
  grid-template-columns: repeat(6, 1fr) !important;
}
```

![columns](https://user-images.githubusercontent.com/24780509/123482248-39553c80-d605-11eb-9fbc-b9b4c83910c9.PNG)

**Comment by gitcatpeter** [comment]
Right, that works; thank you.
