### ISSUE TITLE
How does search bar work?

### ISSUE THREAD

**Issue by gitcatpeter** [pawelmalak/flame#53]
I can type there, but it does not search, nor opens a new tab;  does not react to ENTER etc.

**Comment by pawelmalak** [comment]
You need to use prefix and then type your search query. For example, to search "what is docker" using google search you would type `/g what is docker`. 

Please visit README file for reference.

**Comment by gitcatpeter** [comment]
My bad, I did not check the github main page.

**Comment by pawelmalak** [comment]
Notification with error `Prefix not found` will now be displayed if prefix is incorrect or missing.
