### ISSUE TITLE
[Suggestion] Categories for Applications as well

### ISSUE THREAD

**Issue by beyertom** [pawelmalak/flame#54]
Hi,

is it possible to add categories to the applications as well? As an example you can take a look at Homer (https://github.com/bastienwirtz/homer).

Thank you!

Cheers

**Comment by gitcatpeter** [comment]
Second that. I know the developer sad "no" before, but maybe he could reconsider (make this on/off option).
Again, thank you for the work Pawel.

**Comment by pawelmalak** [comment]
Duplicate of #7 and #32.
You can check out [fdarveau/flame](https://github.com/fdarveau/flame) for this feature.
