### ISSUE TITLE
Flame stopped working

### ISSUE THREAD

**Issue by JaCoB1123** [pawelmalak/flame#55]
I first have to say that I really like flame. It's much easier to configure and looks nicer than Homer which I've been using before.

Unfortunately my flame (running in docker) doesn't start anymore and shows the following logs:

```
[2021-06-27 16:30:32.932 UTC+0] [INFO] Connected to database
[2021-06-27 16:30:32.933 UTC+0] [INFO] Starting model synchronization
[2021-06-27 16:30:32.938 UTC+0] [ERROR] Unable to connect to the database: SQLITE_ERROR: table apps_backup has 7 columns but 8 values were supplied
```

**Comment by pawelmalak** [comment]
Can you show listing of /app/data mounted volume?

**Comment by JaCoB1123** [comment]
```
$ docker-compose run app ls -Al /app/data                                                                                                │
total 96                                                                                                                                                            │
-rwxr-xr-x    1 root     root         94208 Jun 25 02:00 db.sqlite                                                                                                  │
drwxr-xr-x    2 root     root          4096 Jun 25 02:05 uploads
```

**Comment by pawelmalak** [comment]
Are you getting the same error after restart?

**Comment by JaCoB1123** [comment]
Yeah, I tried restarting multiple times and pulled the newest image as well.

**Comment by pawelmalak** [comment]
Here are a few things you can try. First copy `db.sqlite` and save it somewhere else outside mounted volume.

- You can disable model synchronization and check if it changes anything. Console into running container and run `nano db.js`. Change value of: `const syncModels = false;` to `true`, save file and restart the container.
- Open your database file with software like [SQLiteStudio](https://sqlitebrowser.org/). Check how many tables you have. You should have 6 (apps, bookmarks, categories, config, weather, sqlite_sequence). If you have more you can try to drop them, save file and restart the container.
- The last option is to stop container, delete database file and run it again. App will create new file but all data will be gone. If you disabled synchronization you need to re-enable it before stopping container.

**Comment by gitcatpeter** [comment]
This brings a valid point, that flame could invoke a backup prior to making
any changes and keep up to several backups at hand.

**Comment by JaCoB1123** [comment]
I just checked my sqlite db and I have two additional tables apps_backup and bookmarks_backup.
Deleted the two tables and everything is back up running.

Thanks for the help.

@gitcatpeter seems like a good suggestion. If flame cannot start because of a db-issue it could look if a backup exists and use that one.
