### ISSUE TITLE
Docker Hub deployment

### ISSUE THREAD

**Issue by tinjaw** [pawelmalak/flame#60]
I just found this and I want to try it out "quickly and easily". Are you pushing to DockerHub by any chance?

If not, and I start to tinker with this, would you mind if I kept a "test/demo" latest-build on DockerHub for just such a purpose?

**Comment by pawelmalak** [comment]
It is available on Docker Hub since day one: [pawelmalak/flame](https://hub.docker.com/r/pawelmalak/flame)

**Comment by tinjaw** [comment]
Awesome. Thank you.
