### ISSUE TITLE
Add support for non-HTTP(S) bookmarks

### ISSUE THREAD

**Issue by ajmallinson** [pawelmalak/flame#62]
Would it be possible to add support for non-HTTP(S) bookmarks, e.g. Steam. At the moment they can be added to the database just fine but when displaying them back the : (colon) is stripped out of the URL link so they break.

The bookmark appears to be fine in the database as per below screenshots:
![Bookmark in Edit List](https://user-images.githubusercontent.com/7580424/125140779-2feec880-e10b-11eb-976b-408dbb18dc37.JPG)
![Booked in DB Browser](https://user-images.githubusercontent.com/7580424/125140780-30875f00-e10b-11eb-8893-839969d6abbe.JPG)

But when viewing the page the : (colon) has been removed from the link
![Link Target in Edge](https://user-images.githubusercontent.com/7580424/125140782-30875f00-e10b-11eb-86f0-2040ad24948e.JPG)

**Comment by deryaba** [comment]
The same thing happens with `chrome://` links. Is there a possibility to allow any types of links?
There's many schemas like these:
- `chrome://` (it's the issue what I facing with)
- `magnet://` (torrent)
- `rtsp://` (video cams)
- `git://`
- `ftp://` (almost dead, but maybe still used)
- `about:` (I dunno if it's really used nowadays, just remembered about it)

So, [here's](https://en.wikipedia.org/wiki/List_of_URI_schemes) a list of common schemas. It would be nice if you add at least the most commonly used ones =)
