### ISSUE TITLE
Allow users to choose default prefix for search bar

### ISSUE THREAD

**Issue by AzamServer** [pawelmalak/flame#65]
Allow users to choose default prefix for search bar

Example:
User chooses "/g" as default prefix
Users puts "YouTube" in search bar and presses enter
Flame returns output for "/g YouTube"

**Comment by jjack** [comment]
You are in luck! A PR was just approved that does just that.

https://github.com/pawelmalak/flame/pull/61

**Comment by AzamServer** [comment]
Is there a way to change DuckDuckGo as the default search engine?

**Comment by jjack** [comment]
You can change the default by going to `http://flame:5005/settings/other`. Under "Modules" there's a section for "Default Search Provider"

**Comment by jjack** [comment]
I'm wondering now if that should be under a different section, like "App Behavior."

Thoughts, @pawelmalak ?

**Comment by pawelmalak** [comment]
Yes, I already changed that on my local branch. I also changed how the options in select input are rendered. It will now use json file with prefixes which is already used by searchParser instead of hard coding them.

**Comment by AzamServer** [comment]
When will this local branch be available in Docker?

**Comment by pawelmalak** [comment]
> When will this local branch be available in Docker?

Just pushed updated Docker image to the hub. It should be live now.
