### ISSUE TITLE
Weather API Error

### ISSUE THREAD

**Issue by logdotexe** [pawelmalak/flame#68]
When I try to add api key and all other infos, my docker instance log show this:

[ERROR] External API request failed
[ERROR] External API request failed
[ERROR] External API request failed

I tried to disable Synology firewall (I'm running Flame on Synology Docker) and it's worked, so there are any ports to open for a working wheather API? Port 5005 tcp is already open.

**Comment by pawelmalak** [comment]
Not that I'm aware of. If you have access to the terminal on your machine you can try `curl "http://api.weatherapi.com/v1/current.json?key=YOUR_API_KEY&q=0,0"` to check if you can make request outside Flame.

**Comment by logdotexe** [comment]
On my machine terminal curl command work, it returns `{"location":{"name":"Seccion 22-0","region":"Coahuila","country":"Mexico","lat":27.44,"lon":-100.47,"tz_id":"America/Matamoros","localtime_epoch":1627464189,"localtime":"2021-07-28 4:23"},"current":{"last_updated_epoch":1627463700,"last_updated":"2021-07-28 04:15","temp_c":30.1,"temp_f":86.2,"is_day":0,"condition":{"text":"Partly cloudy","icon":"//cdn.weatherapi.com/weather/64x64/night/116.png","code":1003},"wind_mph":17.7,"wind_kph":28.4,"wind_degree":127,"wind_dir":"SE","pressure_mb":1014.0,"pressure_in":30.4,"precip_mm":0.0,"precip_in":0.0,"humidity":46,"cloud":5,"feelslike_c":31.0,"feelslike_f":87.8,"vis_km":10.0,"vis_miles":6.0,"uv":1.0,"gust_mph":25.1,"gust_kph":40.3}}`

**Comment by logdotexe** [comment]
Ok I opened port 80 on my machine firewall and now it works
