### ISSUE TITLE
Not working `chrome://` links and others

### ISSUE THREAD

**Issue by deryaba** [pawelmalak/flame#74]
The same thing happens with `chrome://` links. Is there a possibility to allow any types of links?
There's many schemas like these:
- `chrome://` (it's the issue what I facing with)
- `magnet://` (torrent)
- `rtsp://` (video cams)
- `git://`
- `ftp://` (almost dead, but maybe still used)
- `about:` (I dunno if it's really used nowadays, just remembered about it)

So, [here's](https://en.wikipedia.org/wiki/List_of_URI_schemes) a list of common schemas. It would be nice if you add at least the most commonly used ones =)

_Originally posted by @deryaba in https://github.com/pawelmalak/flame/issues/62#issuecomment-893591262_

**Comment by Samuel-Martineau** [comment]
`about://` is the equivalent of `chrome://` for FireFox

**Comment by deryaba** [comment]
> `about://` is the equivalent of `chrome://` for FireFox

Sorry for belated answer, I was on vacation. =)
The example is chrome://net-internals/#dns. But I do not sure now it is not a problem on Chrome side.
