### ISSUE TITLE
Ability to resize text/screen

### ISSUE THREAD

**Issue by Nelinski** [pawelmalak/flame#8]
It would be useful to have a setting to resize the screen (similar to zooming out on your browser). Sometimes long URLs aren't long enough to merge onto a 2nd line so looks cluttered. This would fix it nicely.

**Comment by gitcatpeter** [comment]
Second that.

Or even widen the whole usable area to one's liking. On wide monitors lots of screen real-estate gets wasted.

**Comment by pawelmalak** [comment]
Probably won't add this as a separate setting but as a part of #17
