### ISSUE TITLE
Blank dashboard after adding new app with custom image

### ISSUE THREAD

**Issue by pngmn** [pawelmalak/flame#83]
I added a new app with an custom image and directly after I added another one with the same image (I didn't upload it again). The dashboard went blank immediately after I pressed add.

Not sure if its related but I get this error in Firefox:
```
TypeError: e[0] is undefined
```
In Edge I get this error:
```
TypeError: Cannot read properties of undefined (reading 'toUpperCase')
    at iconParser.ts:9
    at Array.map (<anonymous>)
    at C (iconParser.ts:9)
    at Ge (AppCard.tsx:38)
    at VL (react-dom.production.min.js:157)
    at Ur (react-dom.production.min.js:267)
    at bi (react-dom.production.min.js:250)
    at gi (react-dom.production.min.js:250)
    at Si (react-dom.production.min.js:250)
    at ai (react-dom.production.min.js:243)
```

This is the entry in the db.sqlite:
![](https://i.imgur.com/EPHXKbD.png)

**Comment by pawelmalak** [comment]
When you add a new app all inputs are being cleared so your second app has been added without any icon.
To fix it on your side you need to remove faulty row from the database or add some value to the icon column.

I'll take a look on how to fix it in the app.

**Comment by frankanderson** [comment]
Is there a way to fix this issue prior to the new version rolling out? My backup seems to have run right after I added the new application.
