### ISSUE TITLE
[Feature Request] Group applications

### ISSUE THREAD

**Issue by AaronPorts** [pawelmalak/flame#85]
I think it would be nice to be able to create app groups.

![1234](https://user-images.githubusercontent.com/32810520/132255537-51022911-7539-4361-9715-289248c21ae0.png)

**Comment by gitcatpeter** [comment]
Absolutely. And same for bookmarks.
And ability to fold groups.
One can dream...lol.

**Comment by pawelmalak** [comment]
Duplicate of #7, #32 and #54.
You can check out [fdarveau/flame](https://github.com/fdarveau/flame) for this feature.
