### ISSUE TITLE
Refreshing page shows default theme (.5sec) before loading selected theme

### ISSUE THREAD

**Issue by Bookingyo** [pawelmalak/flame#88]
If I refresh the page you can see the default theme load before the selected theme does.

**Comment by Bookingyo** [comment]
default theme which loads
![default theme](https://user-images.githubusercontent.com/66762796/133135158-efaf0603-5192-4a49-9e52-5dfe5bfab698.png)
to custom theme
![custom theme](https://user-images.githubusercontent.com/66762796/133135171-d8169089-e727-4441-b560-5353009d7608.png)

**Comment by pawelmalak** [comment]
That's how it works. The "Blues" color theme is set as the default in CSS, and when the app is loaded, the custom theme replaces the original one. 

If it really bothers you, you can download source files, edit [index.css](https://github.com/pawelmalak/flame/blob/master/client/src/index.css) and build your own image.
