### ISSUE TITLE
Custom Icons do not persist when adding apps via docker labels

### ISSUE THREAD

**Issue by BackedUpBooty** [pawelmalak/flame#91]
I have a number of containers which I've set up with the label variables as follows:
```
      - flame.type=application
      - flame.name=exampleApp
      - flame.url=192.168......:port
```
Once inside the flame GUI, I went through and manually changed all the icons to custom icons (generally the relevant service's logo) and it all looked great. But when refreshing the page, all the custom icons disappeared and were replaced by the default docker icon. 

Have I missed something about using the label variables? I know you can set the mdi from them too, is there a way I should be setting the custom icons?

If it makes any difference, the same apps which use labels also get unpinned.

**Comment by pawelmalak** [comment]
@pruizlezcano

**Comment by pruizlezcano** [comment]
There is no option for custom icons. If you don't provide an icon name it puts the default docker icon. I will take a look this week. 

What option would you rather to use, define `flame.icon=custom` in the docker-compose  or not saying nothing about the icon (same as the issue example)?

**Comment by BackedUpBooty** [comment]
Sorry I should have been clearer, I meant when using the custom icon upload in the GUI where you can choose a file;
![image](https://user-images.githubusercontent.com/53868636/134833899-92cbcd6c-6de4-4399-9b30-0980d718c663.png)

But otherwise yeah a defined `flame-icon=custom` would be great! But then you may want to also have to define the icon inside  `/app/data`, so something like `flame.custom.icon.path=/app/data/path/to/icon.png`
