### ISSUE TITLE
Cache icons and fonts for offline use

### ISSUE THREAD

**Issue by dansity** [pawelmalak/flame#94]
Flame is not loading when the internet is down as it is reaching for google api for font and MDI icons. Everything should be cached so no internet required to open a start page.

**Comment by pawelmalak** [comment]
Only fonts are being downloaded. Icons are already embedded in js bundle. I think there is an option to download fonts without blocking the rest of the app, but I need to read more about it.

**Comment by dansity** [comment]
I have only dealt with php, so I don't know about the language you are using here, but when i needed fonts locally i was able to just place fonts in a folder and import them to my site with css with @font-face. Maybe you dont need the google api. Now what I dont know how licensing of the fonts work and if this is permitted. Although there is a lot of open font out there.
