### ISSUE TITLE
[Feature Request] Add TLS/SSL and ability to change port #

### ISSUE THREAD

**Issue by AliceGrey** [pawelmalak/flame#95]
It would be nice to have TLS/SSL as a setting that can be enabled (User would have to upload or copy and paste keys).  It would also be helpful to add the ability to change the port number from the settings.

**Comment by schlaggi** [comment]
As nobody answered for quite some time: I think a reverseproxy is what you should use for SSL/TLS and the port number can be easily changed if you use docker.
Maybe you try that?
